import sqlite3

import pytest

from migrations import v006_tms_execution_events
from migrations.runner import required_migration_head, rollback, upgrade


def _base_schema(connection):
    connection.executescript("""
        PRAGMA foreign_keys=ON;
        CREATE TABLE freight_orders (id TEXT PRIMARY KEY);
        CREATE TABLE delivery_orders (id TEXT PRIMARY KEY);
        INSERT INTO freight_orders(id) VALUES ('FO-1'), ('FO-2');
        INSERT INTO delivery_orders(id) VALUES ('DO-1'), ('DO-2');
    """)


def test_v006_sqlite_schema_matches_execution_models(tmp_path):
    connection = sqlite3.connect(tmp_path / "v006.db")
    _base_schema(connection)
    v006_tms_execution_events.upgrade_sqlite(connection)

    tables = {row[0] for row in connection.execute("SELECT name FROM sqlite_master WHERE type='table'")}
    assert {"transport_events", "transport_event_documents", "freight_order_legacy_links"} <= tables
    event_columns = {row[1] for row in connection.execute('PRAGMA table_info("transport_events")')}
    assert {"eta", "payload_hash", "idempotency_key", "recorded_at", "recorded_by"} <= event_columns
    document_columns = {row[1] for row in connection.execute('PRAGMA table_info("transport_event_documents")')}
    assert {"document_type", "storage_url", "file_name", "mime_type", "checksum", "uploaded_at", "uploaded_by"} <= document_columns

    foreign_keys = {
        (table, row[2], row[3])
        for table in ("transport_events", "transport_event_documents", "freight_order_legacy_links")
        for row in connection.execute(f'PRAGMA foreign_key_list("{table}")')
    }
    assert ("transport_events", "freight_orders", "freight_order_id") in foreign_keys
    assert ("transport_event_documents", "transport_events", "event_id") in foreign_keys
    assert ("freight_order_legacy_links", "delivery_orders", "delivery_order_id") in foreign_keys

    indexes = {row[1]: row[2] for row in connection.execute('PRAGMA index_list("transport_events")')}
    assert indexes["ix_transport_events_order_time"] == 0
    assert indexes["sqlite_autoindex_transport_events_2"] == 1
    index_columns = [row[2] for row in connection.execute('PRAGMA index_info("ix_transport_events_order_time")')]
    assert index_columns == ["freight_order_id", "event_time", "recorded_at"]
    connection.close()


def test_v006_sqlite_upgrade_is_idempotent_and_constraints_are_enforced(tmp_path):
    connection = sqlite3.connect(tmp_path / "constraints.db")
    _base_schema(connection)
    v006_tms_execution_events.upgrade_sqlite(connection)
    v006_tms_execution_events.upgrade_sqlite(connection)
    event = ("EV-1", "FO-1", "check_in", "2026-08-11 07:55:00", 10.8, 106.6, 0, 0,
             "device", "GPS-1", "key-1", "hash-1", "dispatcher")
    connection.execute("""
        INSERT INTO transport_events
          (id, freight_order_id, event_type, event_time, lat, lng, speed_kmh, distance_km,
           source, device_id, idempotency_key, payload_hash, recorded_by)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, event)
    with pytest.raises(sqlite3.IntegrityError):
        connection.execute("""
            INSERT INTO transport_events
              (id, freight_order_id, event_type, event_time, source, idempotency_key, payload_hash, recorded_by)
            VALUES ('EV-2','FO-1','pickup','2026-08-11 08:00:00','manual','key-1','hash-2','dispatcher')
        """)
    connection.execute("INSERT INTO freight_order_legacy_links VALUES ('FO-1','DO-1')")
    with pytest.raises(sqlite3.IntegrityError):
        connection.execute("INSERT INTO freight_order_legacy_links VALUES ('FO-2','DO-1')")
    defaults = {"event_type": "check_in", "source": "manual", "lat": 10, "lng": 106,
                "speed_kmh": 0, "distance_km": 0}
    for column, value in (("event_type", "unknown"), ("source", "satellite"), ("lat", 91),
                          ("lng", 181), ("speed_kmh", -1), ("distance_km", -1)):
        invalid = defaults | {column: value}
        with pytest.raises(sqlite3.IntegrityError):
            connection.execute("""
                INSERT INTO transport_events
                  (id, freight_order_id, event_type, event_time, source, idempotency_key,
                   payload_hash, recorded_by, lat, lng, speed_kmh, distance_km)
                VALUES (?, 'FO-2', ?, '2026-08-11', ?, ?, 'hash', 'actor', ?, ?, ?, ?)
            """, (f"BAD-{column}", invalid["event_type"], invalid["source"], f"key-{column}",
                  invalid["lat"], invalid["lng"], invalid["speed_kmh"], invalid["distance_km"]))
    connection.close()


def test_v006_postgresql_ddl_uses_identity_checks_unique_indexes_and_dependency_order():
    sql = "\n".join(v006_tms_execution_events.statements("postgresql"))
    assert "GENERATED BY DEFAULT AS IDENTITY" in sql
    assert "CONSTRAINT uq_transport_event_idempotency UNIQUE (freight_order_id, idempotency_key)" in sql
    assert "delivery_order_id TEXT NOT NULL UNIQUE REFERENCES delivery_orders(id)" in sql
    assert "payload_hash TEXT NOT NULL" in sql and "eta TEXT" in sql
    assert "CHECK (event_type IN" in sql and "CHECK (source IN ('device', 'manual'))" in sql
    assert "ix_transport_events_order_time" in sql
    rollback_sql = v006_tms_execution_events.statements("postgresql", "rollback")
    assert rollback_sql == [
        "DROP TABLE IF EXISTS transport_event_documents",
        "DROP TABLE IF EXISTS transport_events",
        "DROP TABLE IF EXISTS freight_order_legacy_links",
    ]


def test_runner_rollback_removes_v006_tables_and_marker(tmp_path):
    path = tmp_path / "runner.db"
    connection = sqlite3.connect(path)
    connection.executescript("""
        CREATE TABLE quotations (id TEXT PRIMARY KEY, customer_id TEXT, status TEXT);
        CREATE TABLE sales_orders (id TEXT PRIMARY KEY, customer_id TEXT, status TEXT);
        CREATE TABLE delivery_orders (id TEXT PRIMARY KEY, so_id TEXT, customer_id TEXT, status TEXT);
        CREATE TABLE ar_invoices (id TEXT PRIMARY KEY, do_id TEXT, customer_id TEXT, amount REAL, vat_pct REAL, vat_amount REAL, total REAL, status TEXT);
        CREATE TABLE gl_transactions (id INTEGER PRIMARY KEY AUTOINCREMENT, invoice_id TEXT, date TEXT, account_code TEXT, debit REAL, credit REAL);
    """)
    connection.close()
    assert upgrade(str(path))[-1] == "026_sales_order_lines"
    assert rollback(str(path), restore_from="verified-backup")[0] == "026_sales_order_lines"
    with sqlite3.connect(path) as reverted:
        tables = {row[0] for row in reverted.execute("SELECT name FROM sqlite_master WHERE type='table'")}
        assert not {"transport_event_documents", "transport_events", "freight_order_legacy_links"} & tables
        assert reverted.execute(
            "SELECT 1 FROM schema_migrations WHERE version='006_tms_execution_events'"
        ).fetchone() is None


def test_runner_refuses_rollback_when_v006_contains_business_data(tmp_path):
    path = tmp_path / "valuable.db"
    connection = sqlite3.connect(path)
    connection.executescript("""
        CREATE TABLE quotations (id TEXT PRIMARY KEY, customer_id TEXT, status TEXT);
        CREATE TABLE sales_orders (id TEXT PRIMARY KEY, customer_id TEXT, status TEXT);
        CREATE TABLE delivery_orders (id TEXT PRIMARY KEY, so_id TEXT, customer_id TEXT, status TEXT);
        CREATE TABLE ar_invoices (id TEXT PRIMARY KEY, do_id TEXT, customer_id TEXT, amount REAL, vat_pct REAL, vat_amount REAL, total REAL, status TEXT);
        CREATE TABLE gl_transactions (id INTEGER PRIMARY KEY AUTOINCREMENT, invoice_id TEXT, date TEXT, account_code TEXT, debit REAL, credit REAL);
    """)
    connection.close()
    upgrade(str(path))
    with sqlite3.connect(path) as migrated:
        migrated.execute("INSERT INTO freight_order_legacy_links(freight_order_id,delivery_order_id) VALUES ('FO-X','DO-X')")
        migrated.commit()
    with pytest.raises(RuntimeError, match="restore-from"):
        rollback(str(path))


def test_sqlite_schema_drift_fails_before_v006_marker(tmp_path):
    path = tmp_path / "drift.db"
    connection = sqlite3.connect(path)
    _base_schema(connection)
    connection.execute("CREATE TABLE transport_events (id TEXT PRIMARY KEY, freight_order_id TEXT)")
    connection.execute("CREATE TABLE schema_migrations (version TEXT PRIMARY KEY, applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)")
    connection.commit()
    with pytest.raises(RuntimeError, match="transport_events schema mismatch"):
        v006_tms_execution_events.upgrade_sqlite(connection)
    assert connection.execute(
        "SELECT 1 FROM schema_migrations WHERE version=?", (v006_tms_execution_events.VERSION,)
    ).fetchone() is None
    connection.close()


def test_postgresql_validation_failure_happens_before_v006_marker():
    class Connection:
        def __init__(self): self.sql = []
        def execute(self, statement, params=None):
            sql = str(statement); self.sql.append(sql)
            if sql.startswith("SELECT version"): return []
            if "information_schema.columns" in sql: return []
            return []
    class Begin:
        def __init__(self, connection): self.connection = connection
        def __enter__(self): return self.connection
        def __exit__(self, *_): return False
    class Engine:
        def __init__(self): self.connection = Connection()
        def begin(self): return Begin(self.connection)
    engine = Engine()
    with pytest.raises(RuntimeError, match="transport_events schema mismatch"):
        upgrade("postgresql://not-connected/epl", engine=engine)
    assert not any(
        sql.startswith("INSERT INTO schema_migrations") and "version" in sql
        for sql in engine.connection.sql[engine.connection.sql.index(next(s for s in engine.connection.sql if "transport_events" in s)):]
    )


def _drifted_v006(connection, old, new):
    _base_schema(connection)
    for sql in v006_tms_execution_events.statements("sqlite"):
        sqlite_sql = sql.replace("INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY", "INTEGER PRIMARY KEY AUTOINCREMENT")
        connection.execute(sqlite_sql.replace(old, new))


@pytest.mark.parametrize(("old", "new"), [
    ("recorded_by TEXT NOT NULL", "recorded_by TEXT"),
    ("eta TEXT", "eta INTEGER"),
])
def test_sqlite_validator_rejects_wrong_nullability_or_declared_type(tmp_path, old, new):
    connection = sqlite3.connect(tmp_path / "column-drift.db")
    _drifted_v006(connection, old, new)
    with pytest.raises(RuntimeError, match="schema mismatch"):
        v006_tms_execution_events.validate_sqlite(connection)


def test_sqlite_validator_rejects_missing_numeric_range_check(tmp_path):
    connection = sqlite3.connect(tmp_path / "check-drift.db")
    _drifted_v006(connection, ",\n            CHECK (lat IS NULL OR (lat >= -90 AND lat <= 90))", "")
    with pytest.raises(RuntimeError, match="schema mismatch"):
        v006_tms_execution_events.validate_sqlite(connection)


def test_sqlite_validator_rejects_wrong_fk_target(tmp_path):
    connection = sqlite3.connect(tmp_path / "fk-drift.db")
    _drifted_v006(connection, "event_id TEXT NOT NULL REFERENCES transport_events(id)",
                  "event_id TEXT NOT NULL REFERENCES freight_orders(id)")
    with pytest.raises(RuntimeError, match="schema mismatch"):
        v006_tms_execution_events.validate_sqlite(connection)


def test_sqlite_validator_rejects_missing_legacy_pk_and_unique(tmp_path):
    connection = sqlite3.connect(tmp_path / "key-drift.db")
    _drifted_v006(connection, "freight_order_id TEXT PRIMARY KEY", "freight_order_id TEXT")
    with pytest.raises(RuntimeError, match="schema mismatch"):
        v006_tms_execution_events.validate_sqlite(connection)


@pytest.mark.parametrize(("old", "new"), [
    ("transport_events(freight_order_id, event_time, recorded_at)",
     "transport_events(event_time, freight_order_id, recorded_at)"),
    ("transport_event_documents(event_id)", "transport_event_documents(uploaded_at, event_id)"),
])
def test_sqlite_validator_rejects_wrong_required_index_order(tmp_path, old, new):
    connection = sqlite3.connect(tmp_path / "index-drift.db")
    _drifted_v006(connection, old, new)
    with pytest.raises(RuntimeError, match="schema mismatch"):
        v006_tms_execution_events.validate_sqlite(connection)


@pytest.mark.parametrize(("old", "new"), [
    ("'check_in', 'pickup'", "'check_in', 'bogus'"),
    ("'device', 'manual'", "'device', 'manual', 'partner'"),
])
def test_sqlite_validator_rejects_missing_or_extra_enum_values(tmp_path, old, new):
    connection = sqlite3.connect(tmp_path / "enum-drift.db")
    _drifted_v006(connection, old, new)
    with pytest.raises(RuntimeError, match="schema mismatch"):
        v006_tms_execution_events.validate_sqlite(connection)


@pytest.mark.parametrize("checks", [
    {"event_type": "event_type IN ('check_in','pickup')", "source": "source IN ('device','manual')",
     "lat": "lat IS NULL OR lat >= -90 AND lat <= 90", "lng": "lng IS NULL OR lng >= -180 AND lng <= 180",
     "speed": "speed_kmh IS NULL OR speed_kmh >= 0", "distance": "distance_km IS NULL OR distance_km >= 0"},
    {"event_type": "event_type IN ('check_in','pickup','departure','arrival','unloading','delivered','incident','delay','route_deviation','bogus')",
     "source": "source IN ('device','manual')", "lat": "lat IS NULL OR lat >= -90 AND lat <= 90",
     "lng": "lng IS NULL OR lng >= -180 AND lng <= 180", "speed": "speed_kmh IS NULL OR speed_kmh >= 0",
     "distance": "distance_km IS NULL OR distance_km >= 0"},
])
def test_postgresql_validator_rejects_missing_or_extra_event_enum(checks):
    rows = [("transport_events", name, "CHECK", None, None, None, clause) for name, clause in checks.items()]
    with pytest.raises(RuntimeError, match="schema mismatch"):
        v006_tms_execution_events._validate_postgresql_checks(rows)


def test_postgresql_validator_ignores_postgres_not_null_check_rows_from_related_tables():
    rows = [
        ("transport_event_documents", "doc_event_id_not_null", "CHECK", None, "transport_event_documents", "event_id", "event_id IS NOT NULL"),
        ("freight_order_legacy_links", "link_order_not_null", "CHECK", None, "freight_order_legacy_links", "freight_order_id", "freight_order_id IS NOT NULL"),
        ("transport_events", "event_type", "CHECK", None, None, None,
         "event_type IN ('check_in','pickup','departure','arrival','unloading','delivered','incident','delay','route_deviation')"),
        ("transport_events", "source", "CHECK", None, None, None, "source IN ('device','manual')"),
        ("transport_events", "lat", "CHECK", None, None, None, "lat IS NULL OR lat >= -90 AND lat <= 90"),
        ("transport_events", "lng", "CHECK", None, None, None, "lng IS NULL OR lng >= -180 AND lng <= 180"),
        ("transport_events", "speed", "CHECK", None, None, None, "speed_kmh IS NULL OR speed_kmh >= 0"),
        ("transport_events", "distance", "CHECK", None, None, None, "distance_km IS NULL OR distance_km >= 0"),
    ]
    v006_tms_execution_events._validate_postgresql_checks(rows)


def test_postgresql_validator_accepts_casted_numeric_check_clauses_from_live_postgres():
    rows = [
        ("transport_events", "event_type", "CHECK", None, None, None,
         "(event_type = ANY (ARRAY['check_in'::text, 'pickup'::text, 'departure'::text, 'arrival'::text, 'unloading'::text, 'delivered'::text, 'incident'::text, 'delay'::text, 'route_deviation'::text]))"),
        ("transport_events", "source", "CHECK", None, None, None,
         "(source = ANY (ARRAY['device'::text, 'manual'::text]))"),
        ("transport_events", "lat", "CHECK", None, None, None,
         "((lat IS NULL) OR ((lat >= ('-90'::integer)::double precision) AND (lat <= (90)::double precision)))"),
        ("transport_events", "lng", "CHECK", None, None, None,
         "((lng IS NULL) OR ((lng >= ('-180'::integer)::double precision) AND (lng <= (180)::double precision)))"),
        ("transport_events", "speed", "CHECK", None, None, None,
         "((speed_kmh IS NULL) OR (speed_kmh >= (0)::double precision))"),
        ("transport_events", "distance", "CHECK", None, None, None,
         "((distance_km IS NULL) OR (distance_km >= (0)::double precision))"),
    ]
    v006_tms_execution_events._validate_postgresql_checks(rows)

