import sqlite3

import pytest

from migrations import v005_tms_dispatch_eligibility
from migrations.runner import required_migration_head


def test_v005_creates_dispatch_eligibility_schema(tmp_path):
    assert required_migration_head() == "025_vehicle_depot"
    connection = sqlite3.connect(tmp_path / "v005.db")
    connection.executescript("""
        CREATE TABLE vehicles (id TEXT PRIMARY KEY);
        CREATE TABLE drivers (id TEXT PRIMARY KEY);
        CREATE TABLE locations (id TEXT PRIMARY KEY);
        CREATE TABLE freight_orders (id TEXT PRIMARY KEY);
    """)
    v005_tms_dispatch_eligibility.upgrade_sqlite(connection)

    tables = {row[0] for row in connection.execute("SELECT name FROM sqlite_master WHERE type='table'")}
    assert {"driver_qualifications", "warehouse_appointments", "resource_assignments"} <= tables
    vehicle_columns = {row[1] for row in connection.execute('PRAGMA table_info("vehicles")')}
    assert "pallet_capacity" in vehicle_columns

    # Idempotent for databases whose ORM has already introduced the vehicle column.
    v005_tms_dispatch_eligibility.upgrade_sqlite(connection)
    connection.close()


def test_v005_constraints_reject_invalid_windows(tmp_path):
    connection = sqlite3.connect(tmp_path / "constraints.db")
    connection.executescript("""
        PRAGMA foreign_keys=ON;
        CREATE TABLE vehicles (id TEXT PRIMARY KEY);
        CREATE TABLE drivers (id TEXT PRIMARY KEY);
        CREATE TABLE locations (id TEXT PRIMARY KEY);
        CREATE TABLE freight_orders (id TEXT PRIMARY KEY);
        INSERT INTO locations(id) VALUES ('A');
        INSERT INTO freight_orders(id) VALUES ('FO-1');
    """)
    v005_tms_dispatch_eligibility.upgrade_sqlite(connection)
    with pytest.raises(sqlite3.IntegrityError):
        connection.execute("""
            INSERT INTO warehouse_appointments
                (id, freight_order_id, appointment_type, location_id, scheduled_start, scheduled_end)
            VALUES ('APT-1', 'FO-1', 'invalid', 'A', '2026-08-11 09:00:00', '2026-08-11 08:00:00')
        """)
    connection.close()


def test_v005_postgresql_uses_identity_and_time_indexes():
    sql = "\n".join(v005_tms_dispatch_eligibility.statements("postgresql"))
    assert "GENERATED BY DEFAULT AS IDENTITY" in sql
    assert "ix_resource_assignments_vehicle_time" in sql
    assert "ix_resource_assignments_driver_time" in sql

