# -*- coding: utf-8 -*-
"""Sinh frontend/js/ngon_ngu.js cho EPL Lào.

Nguồn tiếng Việt và tiếng Lào: T_mau.json — bóc nguyên từ bản giao diện mẫu bên Lào đã duyệt
(EPL-Transport-UI.html). KHÔNG sửa chữ Lào của họ. Tiếng Anh thêm ở đây. Khoá mới cho các
màn danh mục/tài khoản thêm ở KHOA_MOI, tiếng Lào ráp từ cụm đã có trong Excel và bản mẫu.
"""
import io
import json
import os

GOC = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NGUON = os.path.join(GOC, 'tools', 'tu_dien_mau_vi_lo.json')       # vi/lo bóc từ bản mẫu bên Lào đã duyệt
DICH = os.path.join(GOC, 'frontend', 'js', 'ngon_ngu.js')

T = json.load(io.open(NGUON, encoding='utf-8'))

EN = {
 'brand': 'EPL Transport Management<small>Ore haulage · Vientiane</small>',
 'nav_dash': 'Overview', 'mod_transport': 'Transport module', 'mod_warehouse': 'Warehouse module', 'mod_system': 'System',
 'nav_tracking': 'Transport slip tracking', 'nav_dispatch': 'Dispatch slip', 'nav_bill': 'Transport bill', 'nav_joint': 'Joint trucks',
 'nav_driver': "Driver trip & water money", 'nav_supplier': 'Supplier tracking', 'nav_fuel': 'Fuel store', 'nav_parts': 'Spare parts store',
 'nav_workflow': 'Workflow & responsibility', 'user_role': 'Thabok yard · Data entry',
 'title_dashboard': 'Overview<span class="sub">Monthly · EPL company</span>',
 'title_tracking': 'Transport slip tracking report<span class="sub">Revenue · Expenses · Status of each trip</span>',
 'title_dispatch': 'Dispatch slip<span class="sub">Entered by role · pick a slip in the toolbar</span>',
 'title_bill': 'Transport bill<span class="sub">Print version · pick a slip in the toolbar</span>',
 'title_joint': 'Joint truck transport report<span class="sub">Outside trucks hauling EPL cargo</span>',
 'title_driver': 'Driver trip & water money<span class="sub">Monthly summary paid with salary</span>',
 'title_supplier': 'Supplier tracking<span class="sub">Payables settled in instalments</span>',
 'title_fuel': 'Fuel store<span class="sub">Thabok store · In – Out – Balance</span>',
 'title_parts': 'Spare parts store<span class="sub">Stock & issues per truck</span>',
 'title_workflow': 'Workflow & responsibility<span class="sub">Who enters – who verifies – who books – who pays</span>',
 'period': 'Period', 'p_aug26': 'August 2026', 'p_sep26': 'September 2026', 'company': 'Ore receiving company', 'all': 'All',
 'export': 'Export report', 'new_dispatch': 'New dispatch slip', 'k_rev': 'Transport revenue', 'k_exp': 'Total expenses',
 'k_tons': 'Tonnage hauled', 'k_unpaid': 'Unpaid by customers', 'trips': 'trips', 'of_total': 'of total',
 'pipe_title': 'Trip progress this period', 'pipe_hint': 'Click a step to filter the list',
 's_dispatched': 'Dispatched', 's_transit': 'In transit', 's_arrived': 'Delivered', 's_unpaid': 'Unpaid', 's_partial': 'Partly paid',
 's_paid': 'Paid', 'p_invoiced': 'Invoiced', 'exp_break': 'Expense breakdown', 'e_fuel': 'Fuel', 'e_travel': 'Travel expenses',
 'e_repair': 'Repairs', 'e_other': 'Other', 'rates': 'Exchange rates (to LAK)', 'attention': 'Needs attention',
 'att1': 'T4-0428-08/EPL – ore bill number missing', 'att2': 'Truck 341 – weight loss 0.76 t (1.8%) above 1.5%',
 'att3': 'Vietnam chipping – instalment 2 due (25/09)', 'att4': '3 delivered slips not yet invoiced',
 'search_ph': 'Search slip no., driver, truck, customer…', 'st_transport': 'Transport status', 'st_finance': 'Finance status',
 'joint_truck': 'Joint truck', 'track_title': 'Transport slips', 'rows': 'rows', 'revenue': 'Revenue (USD)', 'expense': 'Expenses (LAK)',
 'net': 'Net', 'status': 'Status', 'c_date': 'Date', 'c_billno': 'Slip no.', 'c_orebill': 'Ore bill', 'c_route': 'Route',
 'c_company': 'Receiver', 'c_driver': 'Driver', 'c_truck': 'Truck', 'c_plates': 'Head / trailer plates', 'c_customer': 'Customer',
 'c_goods': 'Goods', 'c_trips': 'Trips', 'c_w_origin': 'Origin wt (t)', 'c_w_dest': 'Dest. wt (t)', 'c_price': 'Price/t',
 'c_value': 'Amount', 'c_joint_fee': 'Joint hire', 'c_fee2': '2% fee/slip', 'c_over': 'Overload 1$/t', 'c_fuel': 'Fuel',
 'c_travel': 'Travel', 'c_repair': 'Repairs', 'c_other': 'Other', 'c_totexp': 'Total exp.', 'c_net': 'USD', 'c_st_t': 'Transport',
 'c_st_f': 'Finance', 'track_note': 'Net converted at the rate on the slip date (USD 22,000 · THB 700 · VND 1.2). Click a row to open the dispatch slip.',
 'back_list': 'Slip list', 'print': 'Print', 'save_draft': 'Save draft', 'submit_verify': 'Submit for verification', 'mark_paid': 'Confirm payment received',
 'wf1': 'Data entry', 'wf1d': 'Thabok yard', 'wf2': 'Verification', 'wf2d': 'Vientiane accounting', 'wf3': 'Bookkeeping', 'wf3d': 'I/O accountant',
 'wf4': 'Payment', 'wf4d': 'Treasury / petty cash', 'wf5': 'Invoice', 'wf5d': 'Revenue accountant',
 'doc_dispatch': 'DISPATCH SLIP', 'doc_bill': 'TRANSPORT BILL · ໃບບິນຂົນສົ່ງ', 'doc_no': 'Slip no.',
 'sec1': 'Truck information', 'sec2': 'Transport & revenue information', 'sec3': 'Fuel expenses', 'sec4': 'Travel expenses',
 'sec5': 'Repair expenses', 'sec6': 'Other expenses', 'resp': 'In charge', 'verifier': 'Verifier', 'bookkeeper': 'Bookkeeper', 'payer': 'Payer',
 'r_yard': 'Thabok yard', 'r_fuel_acct': 'Fuel store accountant', 'r_exp_acct': 'Expense accountant', 'r_rev_acct': 'Revenue accountant',
 'r_io_acct': 'I/O accountant (Vientiane)', 'r_treasury': 'Vientiane treasury', 'r_petty': 'Thabok petty cash',
 'acct_entry': 'Account entry', 'acct_1211_70': 'Transport service sales', 'acct_625_371': 'Fuel issued from store', 'acct_code': 'Account code',
 'truck_no': 'Truck no.', 'brand_model': 'Brand / model', 'driver': 'Driver', 'plate_head': 'Tractor plate', 'plate_trailer': 'Trailer plate',
 'd_issue': 'Slip date', 'd_out': 'Departure date', 'd_back': 'Return date', 'days_out': 'Days out', 'days': 'days',
 'odometer': 'Odometer', 'odo_out': 'Out', 'odo_back': 'Back', 'odo_km': 'Km driven', 'customer': 'Customer', 'goods_type': 'Goods type',
 'iron_ore': 'Iron ore', 'other_goods': 'Other goods', 'ore_bill_no': 'Ore bill no.', 'ore_bill_date': 'Ore bill date',
 'origin': 'Origin', 'dest': 'Destination', 'route': 'Route', 'w_origin': 'Origin weight (t)', 'w_dest': 'Destination weight (t)',
 'w_loss': 'Loss', 'ton': 't', 'price_usd': 'Unit price (USD/t)', 'value_usd': 'Amount (USD)', 'value_lak': 'Converted (LAK)',
 'value_rule': 'Amount is computed on the destination weight. Loss above 1.5% is flagged for reconciliation.',
 'item': 'Item', 'qty': 'Qty', 'qty_l': 'Litres', 'unit_price': 'Unit price', 'cur': 'Currency', 'amount': 'Amount', 'amount_lak': 'Amount (LAK)',
 'fill_place': 'Filled at', 'pay_method': 'Payment method', 'note': 'Note', 'total': 'Total', 'add_row': 'Add row', 'diesel': 'Diesel',
 'fp_yard': 'Thabok store', 'fp_vn': 'Vietnam station', 'pm_trip_salary': 'Per trip with salary', 'pm_on_dispatch': 'Paid at dispatch',
 'pm_supplier': 'Supplier credit / instalments', 'pm_card': 'Per trip via card (15M top-up)', 'pm_store': 'Issued from parts store',
 'x_water': 'Water money', 'x_vn': 'Driver expenses in Vietnam', 'x_chip_lao': 'Lao chipping fee (customs yard)', 'x_chip_vn': 'Vietnam chipping fee (1,800,000 VND)',
 'x_bridge': 'Bridge & road fee', 'x_toll': 'Expressway toll', 'x_trip': 'Ore trip money', 'x_phone': 'Phone money', 'x_tire': 'Tyre repair / replacement',
 'x_food': 'Driver meals', 'x_parking': 'Parking / yard fee', 'x_border': 'Border fee', 'x_oil': 'Engine oil change', 'x_brake': 'Brake pads',
 'x_tow': 'Rescue / towing', 'x_misc': 'Other expense', 'x_custom': 'Other (type in)…',
 'edit_hint': 'Every row is editable: change item, quantity, unit price; delete with × or add a new row.',
 'x_air': 'Air-brake chamber part', 'sum_rev': 'Trip revenue (converted)', 'sum_exp': 'Trip expenses', 'sum_net': 'Trip net',
 'sg_driver': 'Driver', 'sg_driver_d': 'Received money & goods', 'sg_issuer': 'Issued by', 'sg_issuer_d': 'Thabok yard', 'sg_verify': 'Verified by',
 'sg_verify_d': 'Vientiane accounting', 'sg_payer': 'Paid by', 'sg_payer_d': 'Treasury / petty cash', 'sg_printer': 'Printed by',
 'sg_filler': 'Fuelled by', 'sg_fuel_check': 'Fuel checked by', 'bill_fuel': 'Fuelling', 'bill_pay': 'Payments', 'pay_driver_total': 'Total payable to driver',
 'grand_total': 'Grand total (LAK)', 'joint_rule': 'Joint truck: owner payout = hire − management fee − overload − EPL advances (EPL fuel, travel).',
 'owner': 'Truck owner', 'pay_owner': 'Owner payout (USD)', 'trip_money': 'Trip money', 'water_money': 'Water money', 'phone_money': 'Phone',
 'vn_money': 'Vietnam expenses', 'total_lak': 'Total (LAK)', 'pay_with': 'Paid via', 'salary': 'With salary', 'cash_dispatch': 'Cash at dispatch',
 'supplier': 'Supplier', 'service': 'Service', 'owed_lak': 'Incurred (LAK)', 'paid_lak': 'Paid', 'balance_lak': 'Balance', 'terms': 'Terms',
 'sup_hint': 'Payables under 625/402 and 614/402', 'sup_chip_lao': 'Customs yard (Lao chipping)', 'sup_chip_vn': 'Vietnam chipping',
 'sup_tire': 'Tyre shop', 'sup_toll': 'Expressway card', 't_monthly': 'Monthly instalments', 't_prepaid': 'Prepaid 15M per top-up',
 'fuel_stock': 'Current stock', 'fuel_out_month': 'Issued this month', 'fuel_avg': 'Average cost', 'fuel_avg_d': 'Weighted average by receipt',
 'ref': 'Document', 'type': 'Type', 'in_l': 'In (L)', 'out_l': 'Out (L)', 'balance_l': 'Balance (L)', 'checked_by': 'Checked by',
 'fs_in': 'Receipt', 'fs_out': 'Issued per slip', 'part': 'Part', 'unit': 'Unit', 'stock': 'Stock', 'min_stock': 'Min. stock',
 'last_issue': 'Last issue', 'u_pc': 'pc', 'u_set': 'set', 'u_l': 'L', 'pt_air': 'Brake air chamber', 'pt_filter': 'Oil filter',
 'pt_tire': 'Tyre 12R22.5', 'pt_brake': 'Brake pads', 'pt_oil': 'Engine oil 15W-40', 'st_ok': 'OK', 'st_low': 'Low',
 'wf_doc1': '1. Dispatch slip', 'wf_doc2': '2. Transport invoice', 'wf_hint': 'From the assignment sheet (ໜ້າວຽກ)', 'wf_invoice': 'Issue transport invoice',
 'wfr1': 'Enter truck data', 'wfr2': 'Enter customer data', 'wfr3': 'Fuel expenses', 'wfr4': 'Travel expenses', 'wfr5': 'Repair expenses', 'wfr6': 'Other expenses',
 'login_as': 'Login:', 'r_acct_vc': 'Vientiane accountant (verification)', 'r_admin': 'Administrator (sees all)',
 'has_expense': 'Has expenses', 'no_expense': 'None on this trip', 'stt_wait': 'Awaiting entry', 'stt_entered': 'Entered · awaiting check',
 'stt_verified': 'Verified · awaiting booking', 'stt_paid': 'Paid', 'stt_na': 'Not applicable', 'readonly': 'View only',
 'hint_yard': 'You are entering as Thabok yard: sections I–VI editable. Accounting and treasury view only.',
 'hint_acct': 'Vientiane accountant: verify sections I, II, IV, V, VI and book them. Yard figures cannot be edited.',
 'hint_fuel': 'Fuel store accountant: works only on section III (verify & book fuel).',
 'hint_cash': 'Treasury / petty cash: pay verified sections IV, V, VI; mark "Paid".',
 'hint_rev': 'Revenue accountant: issue the invoice from section II; expense sections view only.',
 'hint_admin': 'Administrator: view and edit everything.',
 'truck_type': 'Truck type', 'co_epl': 'Company truck (EPL)', 'co_joint': 'Joint (outside) truck', 'ded_title': 'Joint truck hire & deductions',
 'hire_usd': 'Truck hire (USD)', 'fee_pct': 'Management fee (% of hire / slip)', 'fee_amt': 'Fee deducted (USD)', 'limit_t': 'Allowed load (t)',
 'over_t': 'Overload (t)', 'over_p': 'Overload penalty (USD/t)', 'over_amt': 'Overload deducted (USD)',
 'ded_note': 'Overload is computed on destination weight. Deductions and EPL advances are subtracted from the owner payout in the summary below.',
 'who_pays': 'Who pays', 'pay_epl': 'EPL advance', 'pay_own': 'Owner pays', 'fuel_joint_note': 'Joint truck: fuel from the EPL store is deducted from the owner payout. Fuel the owner buys outside is not.',
 'fp_other': 'Outside station (Laos)', 'st_cust_rev': 'Received from customer', 'st_hire': 'Truck hire', 'st_fee': 'Management fee deducted',
 'st_over': 'Overload deducted', 'st_adv': 'Less EPL advances', 'st_adv_fuel': '· EPL store fuel', 'st_adv_travel': '· travel', 'st_adv_repair': '· repairs',
 'st_adv_other': '· other', 'st_net_owner': 'Payable to owner', 'st_profit': 'EPL profit on trip', 'st_own_paid': 'Paid by owner (not counted)',
 'settle_title': 'Joint truck settlement', 'settle_ex': 'Profit = customer amount − truck hire. Owner payout = hire − fee − overload − EPL advances.',
 'pick_bill': 'Pick slip', 'bill_repair': 'Repairs', 'bill_other': 'Other', 'bill_settle': 'Owner settlement',
 'login_title': 'EPL Transport Management', 'login_sub': 'Each user signs in with their own account. Entry, verification, booking, payment and invoicing rights depend on the role.',
 'login_h': 'Sign in', 'login_demo': 'Demo: password for every account is 1234', 'username': 'Username', 'password': 'Password', 'login_btn': 'Sign in',
 'quick_pick': 'Or pick an account:', 'login_err': 'Wrong username or password', 'switch_acct': 'Switch account', 'r_treasury_role': 'Vientiane treasury',
 'hint_treasury': 'Vientiane treasury: confirm fuel payment (section III) after the fuel accountant has booked it.',
 'stt_booked': 'Booked · awaiting payment', 'stt_wait2': 'Not sent', 'a_send': 'Send for verification', 'a_verify': 'Confirm verified', 'a_book': 'Book',
 'a_pay': 'Confirm paid', 'a_return': 'Return for correction', 'a_invoice': 'Issue invoice', 'a_collect': 'Confirm customer paid', 'a_unlock': 'Unlock (admin)',
 'log_title': 'Approval history', 'log_empty': 'No actions yet', 'locked_after': 'Verified – locked', 'inv_done': 'Invoiced', 'trip_status': 'Slip status',
 'acct_625_402': 'Travel expenses', 'acct_614_402': 'Repairs paid to supplier', 'acct_614_371': 'Repairs from store', 'acct_1211_402': 'Outside transport charge',
 'hire_pt': 'Their hire price (USD/t)', 'do_title': 'Profit on this order', 'do_recv': 'Price we receive from customer', 'do_hire': 'What we pay the outside truck',
 'do_diff': 'Rate difference', 'do_cuts': 'Plus owner deductions (fee + overload)', 'do_profit': 'EPL profit', 'per_ton': '/t', 'col_price': 'Price/t',
 'col_tons': 'Tons', 'col_total': 'Amount (USD)', 'do_money': 'Order amount (from customer)', 'trip_profit': 'Profit on this trip',
 'lg_yard': 'Thabok yard (entry)', 'lg_acct': 'Vientiane accounting', 'lg_cash': 'Treasury / cash',
}

# Khoá mới — tiếng Lào ráp từ cụm đã có trong Excel / bản mẫu
KHOA_MOI = {
 'mod_master':       ('Danh mục', 'ຂໍ້ມູນພື້ນຖານ', 'Master data'),
 'nav_customers':    ('Khách hàng', 'ລູກຄ້າ', 'Customers'),
 'nav_vehicles':     ('Xe', 'ພາຫະນະ', 'Vehicles'),
 'nav_drivers':      ('Tài xế', 'ໂຊເຟີ', 'Drivers'),
 'nav_users':        ('Tài khoản', 'ບັນຊີຜູ້ໃຊ້', 'User accounts'),
 'title_khach_hang': ('Khách hàng<span class="sub">Danh mục khách nhận quặng</span>', 'ລູກຄ້າ<span class="sub">ບັນຊີລູກຄ້າຮັບແຮ່</span>', 'Customers<span class="sub">Ore receiving customers</span>'),
 'title_xe':         ('Xe<span class="sub">Số xe · biển đầu kéo · biển rơ-moóc · xe liên kết</span>', 'ພາຫະນະ<span class="sub">ເບີລົດ · ທະບຽນຫົວ · ທະບຽນຫາງ · ລົດຮ່ວມ</span>', 'Vehicles<span class="sub">Truck no. · tractor plate · trailer plate · joint trucks</span>'),
 'title_tai_xe':     ('Tài xế<span class="sub">Danh mục tài xế</span>', 'ໂຊເຟີ<span class="sub">ບັນຊີໂຊເຟີ</span>', 'Drivers<span class="sub">Driver list</span>'),
 'title_tai_khoan':  ('Tài khoản<span class="sub">Người dùng và vai trò</span>', 'ບັນຊີຜູ້ໃຊ້<span class="sub">ຜູ້ໃຊ້ ແລະ ໜ້າທີ່</span>', 'User accounts<span class="sub">Users and roles</span>'),
 'show_pw':  ('Hiện mật khẩu', 'ສະແດງລະຫັດຜ່ານ', 'Show password'),
 'hide_pw':  ('Ẩn mật khẩu', 'ເຊື່ອງລະຫັດຜ່ານ', 'Hide password'),
 # ---- v4: phiếu lĩnh có mã QR · điểm đổ nhiên liệu · cấp phát · tất toán tài xế
 'r_depot':      ('Thủ kho nhiên liệu (một kho)', 'ຜູ້ຮັກສາສາງນໍ້າມັນ (ໜຶ່ງສາງ)', 'Fuel depot keeper (one depot)'),
 'nav_issue':    ('Cấp phát', 'ການຈ່າຍອອກ', 'Issuing'),
 'nav_settle':   ('Tất toán tài xế', 'ສະສາງໂຊເຟີ', 'Driver settlement'),
 'nav_place':    ('Điểm đổ nhiên liệu', 'ສະຖານທີ່ໃສ່ນໍ້າມັນ', 'Fuel places'),
 'title_cap_phat': ('Cấp phát<span class="sub">Phiếu lĩnh đang chờ · quét mã QR của tài xế</span>', 'ການຈ່າຍອອກ<span class="sub">ໃບເບີກລໍຖ້າ · ສະແກນ QR ຂອງໂຊເຟີ</span>', 'Issuing<span class="sub">Pending draw slips · scan the driver QR</span>'),
 'title_tat_toan': ('Tất toán tài xế<span class="sub">Đối tiền ứng và tiền chi theo tháng</span>', 'ສະສາງໂຊເຟີ<span class="sub">ທຽບເງິນລ່ວງໜ້າ ແລະ ເງິນຈ່າຍ ຕາມເດືອນ</span>', 'Driver settlement<span class="sub">Advances against actual spend, by month</span>'),
 'title_diem_do':  ('Điểm đổ nhiên liệu<span class="sub">Kho của EPL và trạm bán dầu bên ngoài</span>', 'ສະຖານທີ່ໃສ່ນໍ້າມັນ<span class="sub">ສາງ EPL ແລະ ປໍ້ານໍ້າມັນທາງນອກ</span>', 'Fuel places<span class="sub">EPL depots and outside stations</span>'),
 'v_fuel':       ('Phiếu lĩnh nhiên liệu', 'ໃບເບີກນໍ້າມັນ', 'Fuel draw slip'),
 'v_advance':    ('Phiếu tạm ứng đi đường', 'ໃບເບີກເງິນລ່ວງໜ້າ', 'Travel advance slip'),
 'v_cho':        ('Chờ cấp', 'ລໍຖ້າຈ່າຍ', 'Pending'),
 'v_da_cap':     ('Đã cấp', 'ຈ່າຍແລ້ວ', 'Issued'),
 'v_huy':        ('Đã huỷ', 'ຍົກເລີກແລ້ວ', 'Cancelled'),
 'v_make_fuel':  ('Lập phiếu lĩnh nhiên liệu', 'ສ້າງໃບເບີກນໍ້າມັນ', 'Create fuel draw slip'),
 'v_make_adv':   ('Lập phiếu tạm ứng', 'ສ້າງໃບເບີກເງິນລ່ວງໜ້າ', 'Create advance slip'),
 'v_none':       ('Chưa lập phiếu lĩnh nào', 'ຍັງບໍ່ໄດ້ສ້າງໃບເບີກ', 'No draw slip yet'),
 'v_qr_hint':    ('Tài xế đưa mã này cho người cấp quét', 'ໂຊເຟີຍື່ນລະຫັດນີ້ໃຫ້ຜູ້ຈ່າຍສະແກນ', 'The driver shows this code to the issuer'),
 'v_code':       ('Mã tra cứu', 'ລະຫັດຄົ້ນຫາ', 'Lookup code'),
 'v_scan':       ('Nhập mã QR', 'ໃສ່ລະຫັດ QR', 'Enter QR code'),
 'v_issue':      ('Cấp', 'ຈ່າຍ', 'Issue'),
 'v_issue_fuel': ('Cấp dầu', 'ຈ່າຍນໍ້າມັນ', 'Issue fuel'),
 'v_issue_cash': ('Chi tiền', 'ຈ່າຍເງິນ', 'Pay cash'),
 'v_qty_real':   ('Số lít cấp thật', 'ຈຳນວນລິດຈ່າຍຈິງ', 'Litres actually issued'),
 'v_qty_ok':     ('Số lít duyệt', 'ຈຳນວນລິດອະນຸມັດ', 'Litres approved'),
 'v_reason':     ('Lý do cấp lệch số duyệt', 'ເຫດຜົນທີ່ຈ່າຍບໍ່ກົງ', 'Reason for the difference'),
 'v_cancel':     ('Huỷ phiếu lĩnh', 'ຍົກເລີກໃບເບີກ', 'Cancel draw slip'),
 'v_empty':      ('Không có phiếu nào đang chờ', 'ບໍ່ມີໃບເບີກລໍຖ້າ', 'Nothing pending'),
 'v_granted_by': ('Người cấp', 'ຜູ້ຈ່າຍ', 'Issued by'),
 'v_check':      ('Đối chiếu trước khi cấp', 'ກວດກ່ອນຈ່າຍ', 'Check before issuing'),
 'v_not_found':  ('Không tìm thấy mã này', 'ບໍ່ພົບລະຫັດນີ້', 'Code not found'),
 'fp_place':     ('Điểm đổ', 'ສະຖານທີ່ໃສ່', 'Fuel place'),
 'fp_epl':       ('Kho của EPL (lĩnh)', 'ສາງ EPL (ເບີກ)', 'EPL depot (draw)'),
 'fp_ngoai':     ('Trạm bán dầu (mua)', 'ປໍ້ານໍ້າມັນ (ຊື້)', 'Outside station (buy)'),
 'fp_la':        ('Lào', 'ລາວ', 'Laos'),
 'fp_vn2':       ('Việt Nam', 'ຫວຽດນາມ', 'Vietnam'),
 'fp_country':   ('Nước', 'ປະເທດ', 'Country'),
 'fp_keeper':    ('Người giữ kho', 'ຜູ້ຮັກສາສາງ', 'Keeper'),
 'fp_pending':   ('Đang chờ cấp', 'ລໍຖ້າຈ່າຍ', 'Pending'),
 'fp_new':       ('Thêm điểm đổ', 'ເພີ່ມສະຖານທີ່', 'Add place'),
 'tt_period':    ('Kỳ (tháng)', 'ໄລຍະ (ເດືອນ)', 'Period (month)'),
 'tt_advanced':  ('Đã ứng', 'ເບີກລ່ວງໜ້າແລ້ວ', 'Advanced'),
 'tt_spent':     ('Đã chi thật', 'ຈ່າຍຈິງ', 'Actually spent'),
 'tt_diff':      ('Chênh lệch', 'ຜົນຕ່າງ', 'Difference'),
 'tt_pay_more':  ('Công ty chi bù', 'ບໍລິສັດຈ່າຍເພີ່ມ', 'Company pays more'),
 'tt_give_back': ('Tài xế nộp lại', 'ໂຊເຟີສົ່ງຄືນ', 'Driver returns'),
 'tt_even':      ('Vừa đủ', 'ພໍດີ', 'Even'),
 'tt_do':        ('Tất toán', 'ສະສາງ', 'Settle'),
 'tt_done':      ('Đã tất toán', 'ສະສາງແລ້ວ', 'Settled'),
 'tt_undo':      ('Bỏ chốt', 'ຍົກເລີກການສະສາງ', 'Reopen'),
 'tt_slips':     ('Phiếu trong kỳ', 'ໃບໃນໄລຍະ', 'Slips in period'),
 'tt_note':      ('Không tính khoản công ty trả thẳng nhà cung cấp theo đợt', 'ບໍ່ນັບລາຍການທີ່ບໍລິສັດຈ່າຍໃຫ້ຜູ້ສະໜອງເປັນງວດ', 'Excludes items the company pays suppliers in batches'),
 'tt_confirm':   ('Tất toán kỳ {ky} cho {ten}?', 'ສະສາງໄລຍະ {ky} ໃຫ້ {ten}?', 'Settle {ky} for {ten}?'),
 'df_declare':   ('Khai đổ nhiên liệu', 'ແຈ້ງການໃສ່ນໍ້າມັນ', 'Declare refuelling'),
 'df_litres':    ('Số lít', 'ຈຳນວນລິດ', 'Litres'),
 'df_where':     ('Đổ ở đâu', 'ໃສ່ຢູ່ໃສ', 'Where'),
 'df_hint':      ('Dầu mua dọc đường (thường bên Việt Nam để chạy về). Kế toán duyệt thì vào mục III.', 'ນໍ້າມັນຊື້ຂ້າງທາງ (ປົກກະຕິຢູ່ຫວຽດນາມເພື່ອຂັບກັບ). ບັນຊີອະນຸມັດແລ້ວຈຶ່ງເຂົ້າພາກ III.', 'Fuel bought on the road (usually in Vietnam for the return leg). Booked into section III once accounting approves.'),
 'ev_refuel':    ('Đổ dầu dọc đường', 'ໃສ່ນໍ້າມັນຂ້າງທາງ', 'Refuelled on the road'),
 # ---- v4b: chạy được khi mất mạng (màn Cấp phát ngoài kho)
 'off_title':   ('Đang ngoại tuyến', 'ກຳລັງອອບລາຍ', 'Offline'),
 'off_hint':    ('Không nối được máy chủ. Đang dùng bản lưu trong máy; việc cấp sẽ tự gửi khi có mạng lại.', 'ຕິດຕໍ່ເຊີບເວີບໍ່ໄດ້. ກຳລັງໃຊ້ຂໍ້ມູນທີ່ເກັບໄວ້ໃນເຄື່ອງ; ການຈ່າຍຈະສົ່ງເມື່ອມີເນັດຄືນ.', 'No connection. Using the copy stored on this device; issues will be sent when the network returns.'),
 'off_queued':  ('{n} việc chờ gửi', '{n} ລາຍການລໍຖ້າສົ່ງ', '{n} waiting to send'),
 'off_sync':    ('Gửi lại ngay', 'ສົ່ງດຽວນີ້', 'Send now'),
 'off_synced':  ('Đã gửi xong {n} việc', 'ສົ່ງສຳເລັດ {n} ລາຍການ', 'Sent {n} item(s)'),
 'off_cached':  ('Bản lưu lúc {luc}', 'ຂໍ້ມູນເກັບເມື່ອ {luc}', 'Stored at {luc}'),
 'off_wait':    ('Chờ gửi', 'ລໍຖ້າສົ່ງ', 'Queued'),
 'off_none':    ('Máy này chưa lưu phiếu nào. Cần nối mạng một lần trước khi ra kho.', 'ເຄື່ອງນີ້ຍັງບໍ່ໄດ້ເກັບໃບໃດ. ຕ້ອງຕໍ່ເນັດເທື່ອໜຶ່ງກ່ອນອອກໄປສາງ.', 'Nothing stored on this device yet. Connect once before going to the depot.'),
 'off_online':  ('Đã có mạng lại', 'ມີເນັດຄືນແລ້ວ', 'Back online'),
 'off_conflict': ('{n} việc bị máy chủ từ chối, xem lại', '{n} ລາຍການຖືກປະຕິເສດ, ກວດຄືນ', '{n} rejected by the server, please review'),
 # ---- v5: màn Theo dõi tuyến dựng theo trung tâm điều hành của EPL_System
 'td_sub':       ('GPS không có — tiến độ từng chặng, sự cố và sửa xe của các phiếu đang chạy.', 'ບໍ່ມີ GPS — ຄວາມຄືບໜ້າແຕ່ລະຊ່ວງ, ເຫດການ ແລະ ການສ້ອມແປງ ຂອງໃບທີ່ກຳລັງແລ່ນ.', 'No GPS — leg progress, incidents and repairs of running slips.'),
 'td_search':    ('Tìm số phiếu, xe, tài xế, khách hàng', 'ຄົ້ນຫາ ເລກໃບ, ລົດ, ໂຊເຟີ, ລູກຄ້າ', 'Search slip, truck, driver, customer'),
 'td_auto':      ('Tự cập nhật 30 giây', 'ອັບເດດເອງ 30 ວິນາທີ', 'Auto refresh 30s'),
 'td_refresh':   ('Cập nhật', 'ອັບເດດ', 'Refresh'),
 'td_book':      ('Sổ sự cố', 'ປຶ້ມເຫດການ', 'Incident log'),
 'td_asof':      ('Dữ liệu máy chủ lúc {luc}', 'ຂໍ້ມູນເຊີບເວີເມື່ອ {luc}', 'Server data at {luc}'),
 'td_running':   ('Phiếu đang chạy', 'ໃບກຳລັງແລ່ນ', 'Running slips'),
 'td_notout':    ('Chưa xuất bến', 'ຍັງບໍ່ທັນອອກ', 'Not departed'),
 'td_long':      ('Đi lâu chưa về', 'ໄປດົນຍັງບໍ່ກັບ', 'Out too long'),
 'td_await_inv': ('Đã tới, chờ hoá đơn', 'ຮອດແລ້ວ, ລໍໃບເກັບເງິນ', 'Arrived, awaiting invoice'),
 'td_open_inc':  ('Sự cố chưa duyệt', 'ເຫດການຍັງບໍ່ອະນຸມັດ', 'Unapproved incidents'),
 'td_unpaid':    ('Chưa thu tiền', 'ຍັງບໍ່ໄດ້ຮັບເງິນ', 'Unpaid'),
 'td_await_iss': ('Phiếu lĩnh chờ cấp', 'ໃບເບີກລໍຖ້າຈ່າຍ', 'Draw slips pending'),
 'td_watch':     ('Chuyến đang theo dõi', 'ຖ້ຽວທີ່ຕິດຕາມ', 'Trips being tracked'),
 'td_by_pri':    ('Ưu tiên', 'ບຸລິມະສິດ', 'Priority'),
 'td_by_date':   ('Ngày đi', 'ວັນທີອອກ', 'Departure'),
 'td_by_cust':   ('Khách hàng', 'ລູກຄ້າ', 'Customer'),
 'td_legs':      ('{toi}/{tong} chặng', '{toi}/{tong} ຊ່ວງ', '{toi}/{tong} legs'),
 'td_days_out':  ('Đi {n} ngày', 'ໄປ {n} ວັນ', 'Out {n} day(s)'),
 'td_inc_open':  ('{n} sự cố chưa duyệt', '{n} ເຫດການຍັງບໍ່ອະນຸມັດ', '{n} incident(s) unapproved'),
 'td_iss_wait':  ('{n} phiếu lĩnh chờ cấp', '{n} ໃບເບີກລໍຖ້າຈ່າຍ', '{n} draw slip(s) pending'),
 'td_profile':   ('Hồ sơ chuyến', 'ຂໍ້ມູນຖ້ຽວ', 'Trip profile'),
 'td_pick':      ('Chọn một chuyến bên trái để xem.', 'ເລືອກຖ້ຽວທາງຊ້າຍເພື່ອເບິ່ງ.', 'Pick a trip on the left.'),
 'td_only_run':  ('Chỉ phiếu chưa xong', 'ສະເພາະໃບຍັງບໍ່ແລ້ວ', 'Unfinished only'),
 'td_sections':  ('Duyệt sáu mục', 'ອະນຸມັດ 6 ພາກ', 'Six sections'),
 'td_none_watch': ('Không có chuyến nào đang theo dõi', 'ບໍ່ມີຖ້ຽວທີ່ຕິດຕາມ', 'No trips being tracked'),
 'td_inc_empty': ('Chưa có sự cố nào', 'ຍັງບໍ່ມີເຫດການ', 'No incidents yet'),
 'err_old_server': ('Máy chủ đang chạy bản cũ nên chưa có chức năng này. Dừng máy chủ (Ctrl+C) rồi chạy lại là xong.', 'ເຊີບເວີກຳລັງແລ່ນລຸ້ນເກົ່າ ຈຶ່ງຍັງບໍ່ມີໜ້າທີ່ນີ້. ຢຸດເຊີບເວີ (Ctrl+C) ແລ້ວແລ່ນໃໝ່ແມ່ນໄດ້.', 'The server is running an older build, so this feature is missing. Stop it (Ctrl+C) and start it again.'),
 # ---- v6: bản đồ tuyến
 'map_title':   ('Bản đồ tuyến', 'ແຜນທີ່ເສັ້ນທາງ', 'Route map'),
 'map_fleet':   ('Đội xe', 'ກອງລົດ', 'Fleet'),
 'map_one':     ('Tuyến đang chọn', 'ເສັ້ນທາງທີ່ເລືອກ', 'Selected route'),
 'map_sat':     ('Vệ tinh', 'ດາວທຽມ', 'Satellite'),
 'map_road':    ('Đường phố', 'ຖະໜົນ', 'Street'),
 'map_running': ('Đang chạy', 'ກຳລັງແລ່ນ', 'Running'),
 'map_late':    ('Đi lâu', 'ໄປດົນ', 'Out long'),
 'map_inc':     ('Có sự cố', 'ມີເຫດການ', 'Incident'),
 'map_nopos':   ('Chưa có vị trí', 'ຍັງບໍ່ມີຕຳແໜ່ງ', 'No position'),
 'map_note':    ('Đường xanh là tuyến kế hoạch. Chấm xe đứng ở mốc đã xác nhận tới gần nhất, không phải vệt GPS.', 'ເສັ້ນສີຟ້າແມ່ນເສັ້ນທາງຕາມແຜນ. ຈຸດລົດຢູ່ບ່ອນທີ່ຢືນຢັນວ່າຮອດຫຼ້າສຸດ, ບໍ່ແມ່ນ GPS.', 'The blue line is the planned route. The truck sits at the last confirmed stop, not a GPS trace.'),
 'map_none':    ('Tuyến này chưa khai toạ độ điểm dừng nên chưa vẽ được bản đồ. Khai ở màn Tuyến đường.', 'ເສັ້ນທາງນີ້ຍັງບໍ່ໄດ້ໃສ່ພິກັດຈຸດຈອດ ຈຶ່ງຍັງບໍ່ທັນແຕ້ມແຜນທີ່. ໃສ່ຢູ່ໜ້າເສັ້ນທາງ.', 'This route has no stop coordinates yet, so no map. Enter them on the Routes screen.'),
 'map_pos_at':  ('Đang ở mốc {ten}', 'ຢູ່ຈຸດ {ten}', 'At stop {ten}'),
 'st_lat':      ('Vĩ độ', 'ລາຕິຈູດ', 'Latitude'),
 'st_lng':      ('Kinh độ', 'ລອງຈິຈູດ', 'Longitude'),
 # ---- v7: GPS thật từ điện thoại tài xế
 'gps_share':   ('Chia sẻ vị trí', 'ແບ່ງປັນຕຳແໜ່ງ', 'Share location'),
 'gps_sharing': ('Đang chia sẻ vị trí', 'ກຳລັງແບ່ງປັນຕຳແໜ່ງ', 'Sharing location'),
 'gps_stop':    ('Ngưng chia sẻ', 'ຢຸດແບ່ງປັນ', 'Stop sharing'),
 'gps_hint':    ('Bật lúc bắt đầu chạy. Máy gửi vị trí về văn phòng để họ thấy xe trên bản đồ. Giữ trang này mở.', 'ເປີດຕອນເລີ່ມແລ່ນ. ເຄື່ອງຈະສົ່ງຕຳແໜ່ງໄປຫ້ອງການເພື່ອເຫັນລົດຢູ່ແຜນທີ່. ເປີດໜ້ານີ້ໄວ້.', 'Turn on when you set off. The phone sends your position to the office so they can see the truck. Keep this page open.'),
 'gps_denied':  ('Máy không cho lấy vị trí. Vào cài đặt trình duyệt bật quyền vị trí rồi thử lại.', 'ເຄື່ອງບໍ່ອະນຸຍາດເອົາຕຳແໜ່ງ. ໄປຕັ້ງຄ່າໂປຣແກຣມທ່ອງເວັບເປີດສິດຕຳແໜ່ງແລ້ວລອງໃໝ່.', 'The phone refused location access. Enable it in the browser settings and try again.'),
 'gps_nosupport': ('Máy này không có chức năng định vị.', 'ເຄື່ອງນີ້ບໍ່ມີລະບົບຫາຕຳແໜ່ງ.', 'This device has no location service.'),
 'gps_last':    ('Gửi lúc {luc}', 'ສົ່ງເມື່ອ {luc}', 'Sent at {luc}'),
 'gps_missing': ('GPS thiếu hoặc cũ', 'GPS ຂາດ ຫຼື ເກົ່າ', 'GPS missing or stale'),
 'gps_age':     ('GPS {n} phút trước', 'GPS {n} ນາທີກ່ອນ', 'GPS {n} min ago'),
 'gps_speed':   ('Tốc độ', 'ຄວາມໄວ', 'Speed'),
 'gps_src_gps': ('Vị trí GPS thật', 'ຕຳແໜ່ງ GPS ຈິງ', 'Live GPS position'),
 'gps_src_moc': ('Theo mốc đã xác nhận tới', 'ຕາມຈຸດທີ່ຢືນຢັນຮອດ', 'At the last confirmed stop'),
 'gps_trail':   ('Vệt đã đi', 'ເສັ້ນທາງທີ່ຜ່ານມາ', 'Trail'),
 'map_note2':   ('Đường xanh đậm là vệt GPS thật của xe; đường xanh nhạt là tuyến kế hoạch.', 'ເສັ້ນສີຟ້າເຂັ້ມແມ່ນເສັ້ນ GPS ຈິງ; ເສັ້ນອ່ອນແມ່ນເສັ້ນທາງຕາມແຜນ.', 'The solid line is the real GPS trail; the pale line is the planned route.'),
 # ---- v8: màn đăng nhập dựng theo bản mẫu đăng nhập anh gửi (đã bỏ khỏi dự án)
 'lg_brand_sub': ('Vận chuyển quặng · Viêng Chăn – Việt Nam', 'ຂົນສົ່ງແຮ່ · ວຽງຈັນ – ຫວຽດນາມ', 'Ore haulage · Vientiane – Vietnam'),
 'lg_s1':       ('Mỏ quặng', 'ບ່ອນຂຸດແຮ່', 'Ore mine'),
 'lg_s2':       ('Bãi EPL', 'ສະໜາມ EPL', 'EPL yard'),
 'lg_s3':       ('Cửa khẩu', 'ດ່ານຊາຍແດນ', 'Border gate'),
 'lg_s4':       ('Cảng', 'ທ່າເຮືອ', 'Port'),
 'lg_badge':    ('Xe đang ở đây', 'ລົດຢູ່ນີ້', 'Truck here'),
 'lg_remember': ('Ghi nhớ đăng nhập', 'ຈື່ການເຂົ້າລະບົບ', 'Remember me'),
 'lg_g_admin':  ('Quản trị', 'ຜູ້ບໍລິຫານ', 'Admin'),
 'lg_g_acct':   ('Kế toán', 'ບັນຊີ', 'Accounting'),
 'lg_g_wh':     ('Bãi và kho', 'ສະໜາມ ແລະ ສາງ', 'Yard and stores'),
 'lg_g_cash':   ('Quỹ', 'ຄັງເງິນ', 'Cash desks'),
 'lg_g_drv':    ('Tài xế', 'ໂຊເຟີ', 'Drivers'),
 # ---- v10: nửa trái màn đăng nhập — dải số liệu, thẻ tính năng có vai trò
 'lg_st1':      ('xe đang chạy', 'ລົດກຳລັງແລ່ນ', 'trucks running'),
 'lg_st2':      ('xe đi lâu', 'ລົດໄປດົນ', 'out too long'),
 'lg_st3':      ('phiếu chờ duyệt', 'ໃບລໍອະນຸມັດ', 'slips to approve'),
 'lg_st4':      ('phiếu lĩnh chờ cấp', 'ໃບເບີກລໍຖ້າຈ່າຍ', 'draw slips pending'),
 'lg_c1_d':     ('Lập phiếu, gán xe và tài xế, in phiếu lĩnh có mã QR', 'ສ້າງໃບ, ກຳນົດລົດ ແລະ ໂຊເຟີ, ພິມໃບເບີກມີ QR', 'Create the slip, assign truck and driver, print QR draw slips'),
 'lg_c2_d':     ('Quét mã, đối chiếu đúng xe rồi cấp dầu, trừ tồn ngay', 'ສະແກນລະຫັດ, ກວດໃຫ້ຖືກລົດ ແລ້ວຈ່າຍນໍ້າມັນ, ຫັກສາງທັນທີ', 'Scan, check the truck, issue fuel and cut stock at once'),
 'lg_c3_d':     ('Duyệt sáu mục, chi tiền, lập hoá đơn và thu tiền khách', 'ອະນຸມັດ 6 ພາກ, ຈ່າຍເງິນ, ອອກໃບເກັບເງິນ ແລະ ຮັບເງິນ', 'Approve six sections, pay out, invoice and collect'),
 'lg_r1':       ('Điều độ', 'ຜູ້ຈັດຖ້ຽວ', 'Dispatch'),
 'lg_r2':       ('Thủ kho', 'ຜູ້ຮັກສາສາງ', 'Storekeeper'),
 'lg_r3':       ('Kế toán', 'ບັນຊີ', 'Accounting'),
 'ok':       ('Đồng ý', 'ຕົກລົງ', 'OK'),
 'cancel':   ('Huỷ', 'ຍົກເລີກ', 'Cancel'),
 'save':     ('Lưu', 'ບັນທຶກ', 'Save'),
 'add':      ('Thêm', 'ເພີ່ມ', 'Add'),
 'edit':     ('Sửa', 'ແກ້ໄຂ', 'Edit'),
 'delete':   ('Xoá', 'ລຶບ', 'Delete'),
 'close':    ('Đóng', 'ປິດ', 'Close'),
 'search':   ('Tìm', 'ຄົ້ນຫາ', 'Search'),
 'actions':  ('Thao tác', 'ການດຳເນີນ', 'Actions'),
 'active':   ('Đang dùng', 'ໃຊ້ຢູ່', 'Active'),
 'inactive': ('Ngưng dùng', 'ຢຸດໃຊ້', 'Inactive'),
 'loading':  ('Đang tải…', 'ກຳລັງໂຫຼດ…', 'Loading…'),
 'no_permission': ('Bạn không có quyền vào màn này', 'ທ່ານບໍ່ມີສິດເຂົ້າໜ້ານີ້', 'You have no permission for this screen'),
 'err_generic': ('Có lỗi xảy ra', 'ເກີດຂໍ້ຜິດພາດ', 'Something went wrong'),
 'saved':    ('Đã lưu', 'ບັນທຶກແລ້ວ', 'Saved'),
 'name':     ('Tên', 'ຊື່', 'Name'),
 'phone':    ('Điện thoại', 'ໂທລະສັບ', 'Phone'),
 'address':  ('Địa chỉ', 'ທີ່ຢູ່', 'Address'),
 'license_no': ('Số bằng lái', 'ເລກໃບຂັບຂີ່', 'Licence no.'),
 'owner_type': ('Loại xe', 'ປະເພດລົດ', 'Truck type'),
 'month':    ('Tháng', 'ເດືອນ', 'Month'),
 'role':     ('Vai trò', 'ໜ້າທີ່', 'Role'),
 'full_name': ('Họ tên', 'ຊື່ ແລະ ນາມສະກຸນ', 'Full name'),
 'new_password': ('Mật khẩu mới (bỏ trống nếu không đổi)', 'ລະຫັດຜ່ານໃໝ່ (ປະຫວ່າງຖ້າບໍ່ປ່ຽນ)', 'New password (leave blank to keep)'),
 'confirm_delete': ('Xoá mục này?', 'ລຶບລາຍການນີ້ບໍ?', 'Delete this item?'),
 'confirm_action': ('Xác nhận thực hiện?', 'ຢືນຢັນການດຳເນີນ?', 'Confirm this action?'),
 'a_create': ('Lập phiếu', 'ສ້າງບິນ', 'Slip created'),
 'a_save':   ('Lưu phiếu', 'ບັນທຶກບິນ', 'Slip saved'),
 'st_dispatched': ('Xe đã xuất bến', 'ລົດອອກແລ້ວ', 'Truck dispatched'),
 'st_transit':    ('Xe đang chạy', 'ກຳລັງຈັດສົ່ງ', 'Truck in transit'),
 'st_arrived':    ('Xe đã tới, đã cân', 'ຮອດແລ້ວ ຊັ່ງແລ້ວ', 'Arrived, weighed'),
 'fin_unpaid':    ('Chưa thu', 'ຄ້າງຊໍາລະ', 'Unpaid'),
 'fin_partial':   ('Thu một phần', 'ຊໍາລະບາງສ່ວນ', 'Partly paid'),
 'fin_paid':      ('Đã thu đủ', 'ຊໍາລະແລ້ວ', 'Fully paid'),
 'mark_transit':  ('Xe đã lăn bánh', 'ລົດອອກເດີນທາງແລ້ວ', 'Truck departed'),
 'mark_arrived':  ('Xe đã tới · nhập cân cuối', 'ລົດຮອດແລ້ວ · ໃສ່ນ້ຳໜັກປາຍທາງ', 'Truck arrived · enter destination weight'),
 'new_slip':      ('Phiếu mới', 'ບິນໃໝ່', 'New slip'),
 'open_slip':     ('Mở phiếu', 'ເປີດບິນ', 'Open slip'),
 'fuel_in':       ('Nhập kho', 'ນຳເຂົ້າສາງ', 'Receive'),
 'fuel_out':      ('Xuất cho xe', 'ເບີກໃຫ້ລົດ', 'Issue to truck'),
 'pay_supplier':  ('Trả nhà cung cấp', 'ຈ່າຍຜູ້ສະໜອງ', 'Pay supplier'),
 'pay_date':      ('Ngày trả', 'ວັນທີຈ່າຽ', 'Payment date'),
 'payments':      ('Các lần trả', 'ລາຍການຈ່າຍ', 'Payments'),
 'no_data':       ('Chưa có dữ liệu', 'ຍັງບໍ່ມີຂໍ້ມູນ', 'No data yet'),
 'weight_dest_prompt': ('Cân cuối (tấn)', 'ນ້ຳໜັກປາຍທາງ (ໂຕນ)', 'Destination weight (t)'),
 'attention_hao_hut': ('{doc_no} – hao hụt cân {gia_tri}% vượt mức 1,5%', '{doc_no} – ຫາຍເກີນ {gia_tri}% (ເກີນ 1,5%)', '{doc_no} – weight loss {gia_tri}% above 1.5%'),
 'attention_chua_hoa_don': ('{doc_no} – đã giao nhưng chưa lập hoá đơn', '{doc_no} – ຮອດແລ້ວ ແຕ່ຍັງບໍ່ອອກໃບບິນ', '{doc_no} – delivered but not invoiced'),
 'attention_chua_can': ('{doc_no} – đã tới nhưng chưa nhập cân cuối', '{doc_no} – ຮອດແລ້ວ ແຕ່ຍັງບໍ່ໃສ່ນ້ຳໜັກປາຍທາງ', '{doc_no} – arrived but destination weight missing'),
 'attention_cho_kiem': ('{so} mục đã nhập đang chờ kế toán kiểm', '{so} ລາຍການລໍຖ້າບັນຊີກວດ', '{so} entered sections awaiting verification'),
 'none_attention': ('Không có việc cần xử lý', 'ບໍ່ມີວຽກຄ້າງ', 'Nothing needs attention'),
 'sections_status': ('Trạng thái các mục', 'ສະຖານະລາຍການ', 'Section status'),
 'stock_moves': ('Nhập / xuất', 'ນຳເຂົ້າ / ເບີກ', 'Movements'),
 'trip_doc_no': ('Theo phiếu', 'ຕາມບິນ', 'Per slip'),
 # ---- tuyến đường
 'nav_routes':       ('Tuyến đường', 'ເສັ້ນທາງ', 'Routes'),
 'title_tuyen_duong': ('Tuyến đường<span class="sub">Chặng A → B → C · km từng chặng · phí cao tốc (BOT)</span>', 'ເສັ້ນທາງ<span class="sub">ຊ່ວງ A → B → C · ກິໂລແມັດແຕ່ລະຊ່ວງ · ຄ່າທາງດ່ວນ</span>', 'Routes<span class="sub">Legs A → B → C · km per leg · toll (BOT)</span>'),
 'route_name':   ('Tên tuyến', 'ຊື່ເສັ້ນທາງ', 'Route name'),
 'stops':        ('Các điểm trên tuyến', 'ຈຸດຕາມເສັ້ນທາງ', 'Stops'),
 'stop':         ('Điểm', 'ຈຸດ', 'Stop'),
 'km_from_prev': ('Km từ điểm trước', 'ກິໂລແມັດຈາກຈຸດກ່ອນ', 'Km from previous'),
 'total_km':     ('Tổng km', 'ລວມກິໂລແມັດ', 'Total km'),
 'toll_bot':     ('Phí cao tốc (BOT) cả tuyến', 'ຄ່າທາງດ່ວນທັງເສັ້ນ', 'Expressway toll (BOT) for route'),
 'add_stop':     ('Thêm điểm', 'ເພີ່ມຈຸດ', 'Add stop'),
 'pick_route':   ('Chọn tuyến', 'ເລືອກເສັ້ນທາງ', 'Pick route'),
 'route_hint':   ('Chọn tuyến thì điểm đi / điểm đến tự điền và phí cao tốc tự thành một dòng chi phí đi đường.', 'ເລືອກເສັ້ນທາງ ຕົ້ນທາງ/ປາຍທາງ ຈະຖືກຕື່ມເອງ ແລະ ຄ່າທາງດ່ວນຈະເປັນລາຍຈ່າຍເດີນທາງເອງ.', 'Picking a route fills origin/destination and adds the toll as a travel expense line.'),
 # ---- theo dõi tuyến
 'nav_track_route':  ('Theo dõi tuyến', 'ຕິດຕາມເສັ້ນທາງ', 'Route tracking'),
 'title_theo_doi_tuyen': ('Theo dõi tuyến<span class="sub">Xe đang ở chặng nào · sự cố · sửa xe trên đường</span>', 'ຕິດຕາມເສັ້ນທາງ<span class="sub">ລົດຢູ່ຊ່ວງໃດ · ເຫດການ · ສ້ອມແປງລະຫວ່າງທາງ</span>', 'Route tracking<span class="sub">Which leg the truck is on · incidents · roadside repairs</span>'),
 'progress':     ('Tiến độ trên tuyến', 'ຄວາມຄືບໜ້າຕາມເສັ້ນທາງ', 'Progress on route'),
 'events':       ('Diễn biến', 'ເຫດການ', 'Events'),
 'mark_stop':    ('Xe đã tới điểm này', 'ລົດຮອດຈຸດນີ້ແລ້ວ', 'Truck reached this stop'),
 'report_incident': ('Báo sự cố / sửa xe', 'ແຈ້ງເຫດການ / ສ້ອມແປງ', 'Report incident / repair'),
 'add_note':     ('Ghi chú diễn biến', 'ບັນທຶກເຫດການ', 'Add note'),
 'ev_arrive_stop': ('Tới điểm', 'ຮອດຈຸດ', 'Reached stop'),
 'ev_incident':  ('Sự cố', 'ເຫດການ', 'Incident'),
 'ev_repair':    ('Sửa xe', 'ສ້ອມແປງ', 'Repair'),
 'ev_note':      ('Ghi chú', 'ໝາຍເຫດ', 'Note'),
 'incident_type': ('Loại sự cố', 'ປະເພດເຫດການ', 'Incident type'),
 'inc_breakdown': ('Hỏng xe', 'ລົດເສຍ', 'Breakdown'),
 'inc_accident': ('Tai nạn', 'ອຸບັດເຫດ', 'Accident'),
 'inc_delay':    ('Chậm / chờ', 'ຊ້າ / ລໍຖ້າ', 'Delay'),
 'inc_other':    ('Khác', 'ອື່ນໆ', 'Other'),
 'has_repair_cost': ('Có chi phí sửa xe', 'ມີຄ່າສ້ອມແປງ', 'Has repair cost'),
 'source':       ('Nguồn', 'ແຫຼ່ງ', 'Source'),
 'src_kho':      ('Lấy từ kho (xuất kho)', 'ເບີກຈາກສາງ', 'From stock (stock issue)'),
 'src_mua':      ('Mua ngoài / garage (chi tiền)', 'ຊື້ນອກ / ອູ່ (ຈ່າຍເງິນ)', 'Bought outside / garage (payment)'),
 'src_rule':     ('Có trong kho thì xuất kho (TK …/371); không có thì chi mua ngoài (TK …/402).', 'ມີໃນສາງ → ເບີກສາງ (…/371); ບໍ່ມີ → ຈ່າຍຊື້ນອກ (…/402).', 'In stock → stock issue (acct …/371); otherwise → purchase (acct …/402).'),
 'pick_part':    ('Phụ tùng trong kho', 'ອາໄຫຼ່ໃນສາງ', 'Part in stock'),
 'stock_left':   ('Tồn', 'ຍັງເຫຼືອ', 'In stock'),
 'a_reopen':     ('Mở lại để kiểm (có chi mới)', 'ເປີດຄືນເພື່ອກວດ (ມີລາຍຈ່າຍໃໝ່)', 'Reopened for check (new expense)'),
 'reopen_note':  ('Sửa xe khai ở đây sẽ thành một dòng chi trong mục V của phiếu; mục V quay về "chờ kiểm".', 'ການສ້ອມແປງທີ່ແຈ້ງບ່ອນນີ້ ຈະເປັນລາຍຈ່າຍໃນຂໍ້ V ຂອງບິນ; ຂໍ້ V ກັບໄປ "ລໍຖ້າກວດ".', 'A repair declared here becomes a line in section V of the slip; section V goes back to "awaiting check".'),
 'no_route':     ('Phiếu chưa chọn tuyến — vào Phiếu xuất xe, mục II, chọn tuyến.', 'ບິນຍັງບໍ່ເລືອກເສັ້ນທາງ — ເຂົ້າໃບເບີກລົດ ຂໍ້ II ເລືອກເສັ້ນທາງ.', 'No route on this slip — open the dispatch slip, section II, pick a route.'),
 'in_transit_only': ('Chỉ phiếu đang chạy', 'ສະເພາະບິນທີ່ກຳລັງແລ່ນ', 'In-transit slips only'),
 # ---- xe: đầu kéo & rơ-moóc
 'tractors':     ('Đầu kéo', 'ຫົວລົດ', 'Tractors'),
 'trailers':     ('Rơ-moóc', 'ຫາງລົດ', 'Trailers'),
 'trailer':      ('Rơ-moóc', 'ຫາງລົດ', 'Trailer'),
 'plate':        ('Biển số', 'ທະບຽນ', 'Plate'),
 'trailer_type': ('Loại rơ-moóc', 'ປະເພດຫາງ', 'Trailer type'),
 'capacity_t':   ('Tải trọng (tấn)', 'ນ້ຳໜັກບັນທຸກ (ໂຕນ)', 'Capacity (t)'),
 'year':         ('Năm SX', 'ປີຜະລິດ', 'Year'),
 'attach_trailer': ('Lắp rơ-moóc', 'ຕິດຫາງ', 'Attach trailer'),
 'detach_trailer': ('Tháo rơ-moóc', 'ຖອດຫາງ', 'Detach trailer'),
 'attached_to':  ('Đang lắp vào', 'ຕິດຢູ່ກັບ', 'Attached to'),
 'not_attached': ('Chưa lắp xe nào', 'ຍັງບໍ່ຕິດລົດ', 'Not attached'),
 'swap_reason':  ('Lý do tháo / đổi', 'ເຫດຜົນຖອດ / ປ່ຽນ', 'Reason for swap'),
 'trailer_history': ('Lịch sử lắp / tháo rơ-moóc', 'ປະຫວັດຕິດ / ຖອດຫາງ', 'Trailer attach / detach history'),
 'attached_at':  ('Lắp ngày', 'ຕິດວັນທີ', 'Attached'),
 'detached_at':  ('Tháo ngày', 'ຖອດວັນທີ', 'Detached'),
 'engine_no':    ('Số máy', 'ເລກຈັກ', 'Engine no.'),
 'chassis_no':   ('Số khung', 'ເລກຖັງ', 'Chassis no.'),
 'insurance_exp': ('Hạn bảo hiểm', 'ປະກັນໄພໝົດອາຍຸ', 'Insurance expiry'),
 'inspection_exp': ('Hạn đăng kiểm', 'ກວດສະພາບໝົດອາຍຸ', 'Inspection expiry'),
 'road_permit_exp': ('Hạn giấy lưu hành', 'ໃບອະນຸຍາດແລ່ນໝົດອາຍຸ', 'Road permit expiry'),
 'odometer_km':  ('Công-tơ-mét (km)', 'ເລກກົງເຕີ (ກມ)', 'Odometer (km)'),
 'next_service_km': ('Mốc bảo dưỡng kế tiếp (km)', 'ບຳລຸງຮັກສາຄັ້ງຕໍ່ໄປ (ກມ)', 'Next service (km)'),
 'depot':        ('Bãi đậu', 'ສະໜາມຈອດ', 'Depot'),
 'docs_status':  ('Giấy tờ', 'ເອກະສານ', 'Documents'),
 'doc_ok':       ('Còn hạn', 'ຍັງບໍ່ໝົດອາຍຸ', 'Valid'),
 'doc_soon':     ('Sắp hết hạn', 'ໃກ້ໝົດອາຍຸ', 'Expiring soon'),
 'doc_expired':  ('Đã hết hạn', 'ໝົດອາຍຸແລ້ວ', 'Expired'),
 'doc_none':     ('Chưa khai', 'ຍັງບໍ່ລົງ', 'Not entered'),
 'service_due':  ('Đến kỳ bảo dưỡng', 'ຮອດກຳນົດບຳລຸງຮັກສາ', 'Service due'),
 'repairs_of_vehicle': ('Chi phí sửa chữa (từ mục V các phiếu)', 'ຄ່າສ້ອມແປງ (ຈາກຂໍ້ V ຂອງບິນ)', 'Repair costs (from section V of slips)'),
 'trips_count':  ('Số phiếu đã chạy', 'ຈຳນວນບິນ', 'Slips'),
 'v_available':  ('Rảnh', 'ຫວ່າງ', 'Available'),
 'v_on_trip':    ('Đang chạy', 'ກຳລັງແລ່ນ', 'On trip'),
 'v_maintenance': ('Đang sửa', 'ກຳລັງສ້ອມ', 'In maintenance'),
 'v_inactive':   ('Ngưng dùng', 'ຢຸດໃຊ້', 'Inactive'),
 'v_attached':   ('Đang lắp', 'ຕິດຢູ່', 'Attached'),
 'profile':      ('Hồ sơ', 'ຂໍ້ມູນ', 'Profile'),
 'back':         ('Quay lại', 'ກັບຄືນ', 'Back'),
 # ---- tài xế & bằng lái
 'driver_code':  ('Mã tài xế', 'ລະຫັດໂຊເຟີ', 'Driver code'),
 'dob':          ('Ngày sinh', 'ວັນເດືອນປີເກີດ', 'Date of birth'),
 'id_card':      ('Số CMND / căn cước', 'ເລກບັດປະຈຳຕົວ', 'ID card no.'),
 'hire_date':    ('Ngày vào làm', 'ວັນທີເຂົ້າວຽກ', 'Hire date'),
 'driver_role':  ('Vai trên xe', 'ໜ້າທີ່ໃນລົດ', 'Role on truck'),
 'role_main':    ('Lái chính', 'ຂັບຫຼັກ', 'Main driver'),
 'role_co':      ('Phụ xe', 'ຜູ້ຊ່ວຍ', 'Co-driver'),
 'license':      ('Bằng lái', 'ໃບຂັບຂີ່', 'Licence'),
 'licenses':     ('Bằng lái & gia hạn', 'ໃບຂັບຂີ່ ແລະ ການຕໍ່ອາຍຸ', 'Licences & renewals'),
 'license_type': ('Hạng bằng', 'ປະເພດໃບຂັບຂີ່', 'Licence class'),
 'license_valid_from': ('Ngày cấp', 'ວັນທີອອກ', 'Issued on'),
 'license_valid_to': ('Hạn bằng lái', 'ໃບຂັບຂີ່ໝົດອາຍຸ', 'Licence expiry'),
 'issued_by':    ('Nơi cấp', 'ອອກໂດຍ', 'Issued by'),
 'add_license':  ('Ghi bằng lái mới / gia hạn', 'ລົງໃບຂັບຂີ່ໃໝ່ / ຕໍ່ອາຍຸ', 'Add licence / renewal'),
 'default_vehicle': ('Xe thường lái', 'ລົດປະຈຳ', 'Usual truck'),
 'd_available':  ('Rảnh', 'ຫວ່າງ', 'Available'),
 'd_on_trip':    ('Đang chạy', 'ກຳລັງແລ່ນ', 'On trip'),
 'd_leave':      ('Nghỉ', 'ພັກ', 'On leave'),
 'd_inactive':   ('Ngưng làm', 'ຢຸດວຽກ', 'Inactive'),
 'recent_trips': ('Phiếu gần đây', 'ບິນຫຼ້າສຸດ', 'Recent slips'),
 'verified_by':  ('Người kiểm', 'ຜູ້ກວດ', 'Verified by'),
 # ---- vai tài xế & luồng tạm ứng → xuất phát → báo hỏng → duyệt
 'r_driver':     ('Tài xế (chỉ phiếu của mình)', 'ໂຊເຟີ (ສະເພາະບິນຂອງຕົນ)', 'Driver (own slips only)'),
 'nav_my_slips': ('Phiếu của tôi', 'ບິນຂອງຂ້ອຍ', 'My slips'),
 'title_phieu_cua_toi': ('Phiếu của tôi<span class="sub">Nhận tiền tạm ứng · Xuất phát · Báo hỏng trên đường</span>', 'ບິນຂອງຂ້ອຍ<span class="sub">ຮັບເງິນລ່ວງໜ້າ · ອອກລົດ · ແຈ້ງລົດເສຍ</span>', 'My slips<span class="sub">Cash advance · Depart · Report breakdown</span>'),
 'hint_driver':  ('Tài xế: xem phiếu của mình, bấm "Xuất phát" sau khi đã nhận tiền tạm ứng, "Báo hỏng" khi có sự cố trên đường.', 'ໂຊເຟີ: ເບິ່ງບິນຂອງຕົນ, ກົດ "ອອກລົດ" ຫຼັງຮັບເງິນລ່ວງໜ້າ, "ແຈ້ງລົດເສຍ" ເມື່ອມີເຫດການ.', 'Driver: see your slips, press "Depart" after receiving the advance, "Report breakdown" on the road.'),
 'advance':      ('Tiền tạm ứng', 'ເງິນລ່ວງໜ້າ', 'Cash advance'),
 'advance_received': ('Đã nhận tiền', 'ຮັບເງິນແລ້ວ', 'Advance received'),
 'advance_pending': ('Chưa nhận tiền — chờ duyệt / chi', 'ຍັງບໍ່ໄດ້ຮັບເງິນ — ລໍຖ້າກວດ / ຈ່າຍ', 'Advance not yet paid — awaiting approval / payment'),
 'depart':       ('Xuất phát', 'ອອກລົດ', 'Depart'),
 'depart_blocked': ('Chưa nhận tiền tạm ứng thì chưa xuất phát', 'ຍັງບໍ່ໄດ້ຮັບເງິນລ່ວງໜ້າ ບໍ່ສາມາດອອກລົດ', 'Cannot depart before the cash advance is paid'),
 'report_breakdown': ('Báo hỏng / sự cố', 'ແຈ້ງລົດເສຍ / ເຫດການ', 'Report breakdown / incident'),
 'reported_cost': ('Số tiền dự kiến', 'ຈຳນວນເງິນຄາດຄະເນ', 'Estimated cost'),
 'what_broke':   ('Hỏng gì / việc gì', 'ເສຍຫຍັງ / ເກີດຫຍັງ', 'What happened'),
 'st_reported':  ('Chờ duyệt', 'ລໍຖ້າອະນຸມັດ', 'Awaiting approval'),
 'st_approved':  ('Đã duyệt', 'ອະນຸມັດແລ້ວ', 'Approved'),
 'st_rejected':  ('Từ chối', 'ປະຕິເສດ', 'Rejected'),
 'pending_reports': ('Báo hỏng chờ duyệt', 'ແຈ້ງລົດເສຍລໍຖ້າອະນຸມັດ', 'Breakdown reports awaiting approval'),
 'approve':      ('Duyệt', 'ອະນຸມັດ', 'Approve'),
 'reject':       ('Từ chối', 'ປະຕິເສດ', 'Reject'),
 'approve_note': ('Duyệt xong, hệ tự thêm dòng sửa chữa vào mục V của phiếu với số tiền duyệt.', 'ອະນຸມັດແລ້ວ ລະບົບຈະເພີ່ມລາຍຈ່າຍສ້ອມແປງເຂົ້າຂໍ້ V ຂອງບິນຕາມຈຳນວນທີ່ອະນຸມັດ.', 'On approval the system adds a repair line to section V with the approved amount.'),
 'ev_reported':  ('Tài xế báo hỏng', 'ໂຊເຟີແຈ້ງລົດເສຍ', 'Driver reported breakdown'),
 'ev_approved':  ('Duyệt báo hỏng → vào mục V', 'ອະນຸມັດແຈ້ງລົດເສຍ → ຂໍ້ V', 'Breakdown approved → section V'),
 'ev_rejected':  ('Từ chối báo hỏng', 'ປະຕິເສດແຈ້ງລົດເສຍ', 'Breakdown report rejected'),
 'reject_reason': ('Lý do từ chối', 'ເຫດຜົນປະຕິເສດ', 'Reason for rejection'),
 'my_trip_status': ('Chuyến của tôi', 'ຖ້ຽວຂອງຂ້ອຍ', 'My trip'),
 'no_my_slips':  ('Bạn chưa có phiếu xuất xe nào', 'ທ່ານຍັງບໍ່ມີໃບເບີກລົດ', 'You have no dispatch slips'),
 # ---- chứng từ: phiếu chi tạm ứng & phiếu thu
 'nav_vouchers': ('Phiếu chi · Phiếu thu', 'ໃບຈ່າຍ · ໃບຮັບເງິນ', 'Payment · Receipt vouchers'),
 'title_chung_tu': ('Phiếu chi tạm ứng & Phiếu thu<span class="sub">Mỗi giai đoạn một chứng từ · in cho tài xế / kế toán</span>', 'ໃບຈ່າຍເງິນລ່ວງໜ້າ ແລະ ໃບຮັບເງິນ<span class="sub">ແຕ່ລະຂັ້ນຕອນມີເອກະສານ · ພິມໃຫ້ໂຊເຟີ / ບັນຊີ</span>', 'Advance payment & receipt vouchers<span class="sub">One voucher per stage · print for driver / accounting</span>'),
 'voucher_payment': ('Phiếu chi tạm ứng', 'ໃບຈ່າຍເງິນລ່ວງໜ້າ', 'Advance payment voucher'),
 'voucher_receipt': ('Phiếu thu', 'ໃບຮັບເງິນ', 'Receipt voucher'),
 'voucher_no':   ('Số chứng từ', 'ເລກທີເອກະສານ', 'Voucher no.'),
 'payee':        ('Người nhận tiền', 'ຜູ້ຮັບເງິນ', 'Payee'),
 'payer_name':   ('Người nộp tiền', 'ຜູ້ຈ່າຍເງິນ', 'Payer'),
 'amount_words': ('Bằng chữ', 'ເປັນຕົວອັກສອນ', 'In words'),
 'purpose':      ('Nội dung', 'ເນື້ອໃນ', 'Purpose'),
 'purpose_advance': ('Tạm ứng chi phí chuyến {doc_no}: {tuyen}', 'ເງິນລ່ວງໜ້າຄ່າໃຊ້ຈ່າຍຖ້ຽວ {doc_no}: {tuyen}', 'Cash advance for trip {doc_no}: {tuyen}'),
 'purpose_receipt': ('Thu tiền cước vận chuyển phiếu {doc_no}: {tuyen}', 'ຮັບເງິນຄ່າຂົນສົ່ງບິນ {doc_no}: {tuyen}', 'Freight payment for slip {doc_no}: {tuyen}'),
 'voucher_stage': ('Trạng thái chứng từ', 'ສະຖານະເອກະສານ', 'Voucher status'),
 'not_invoiced_yet': ('Chưa lập hoá đơn — mục II phải được kiểm xong', 'ຍັງບໍ່ອອກໃບບິນ — ຂໍ້ II ຕ້ອງກວດແລ້ວ', 'Not invoiced yet — section II must be verified first'),
 'sg_receiver':  ('Người nhận', 'ຜູ້ຮັບ', 'Received by'),
 'sg_cashier':   ('Thủ quỹ', 'ພະນັກງານຄັງເງິນ', 'Cashier'),
 'sg_chief_acct': ('Kế toán trưởng', 'ຫົວໜ້າບັນຊີ', 'Chief accountant'),
 'sg_director':  ('Giám đốc', 'ຜູ້ອຳນວຍການ', 'Director'),
 'no_advance_lines': ('Phiếu này không có khoản tạm ứng tiền mặt (mọi chi đều từ kho hoặc chủ xe tự trả).', 'ບິນນີ້ບໍ່ມີເງິນລ່ວງໜ້າ (ລາຍຈ່າຍທັງໝົດຈາກສາງ ຫຼື ເຈົ້າຂອງລົດຈ່າຍເອງ).', 'This slip has no cash advance lines (everything from stock or paid by the owner).'),
 # ---- định khoản từ API anh Khang
 'acct_pair':    ('Định khoản (Nợ / Có)', 'ບັນຊີ (ໜີ້ / ມີ)', 'Account entry (Dr / Cr)'),
 'acct_debit':   ('Tài khoản Nợ', 'ບັນຊີໜີ້', 'Debit account'),
 'acct_credit':  ('Tài khoản Có', 'ບັນຊີມີ', 'Credit account'),
 'acct_source_remote': ('Danh mục từ API kế toán (anh Khang)', 'ບັນຊີຈາກ API ບັນຊີ', 'Catalogue from accounting API'),
 'acct_source_fallback': ('Chưa nối được API kế toán — đang dùng bản tạm từ Excel', 'ຍັງເຊື່ອມ API ບັນຊີບໍ່ໄດ້ — ໃຊ້ບັນຊີຊົ່ວຄາວຈາກ Excel', 'Accounting API unreachable — using temporary list from Excel'),
 'acct_not_in_catalogue': ('không có trong danh mục', 'ບໍ່ມີໃນບັນຊີ', 'not in catalogue'),
 'acct_search':  ('Gõ mã hoặc tên tài khoản…', 'ພິມລະຫັດ ຫຼື ຊື່ບັນຊີ…', 'Type account code or name…'),
 # ---- v5: sổ chứng từ (điểm nối kế toán) · km về ước tính · ẩn ô tiền với Bãi
 'odo_est':      ('Km về ước tính', 'ກມ ກັບ ຄາດຄະເນ', 'Est. return odometer'),
 'ct_so':        ('Sổ chứng từ', 'ປື້ມເອກະສານ', 'Document register'),
 'ct_loai':      ('Loại chứng từ', 'ປະເພດເອກະສານ', 'Document type'),
 'ct_tu':        ('Từ ngày', 'ແຕ່ວັນທີ', 'From'),
 'ct_den':       ('Đến ngày', 'ຖຶງວັນທີ', 'To'),
 'ct_chua_day':  ('Chưa đối chiếu', 'ຍັງບໍ່ກວດສອບ', 'Not reconciled'),
 'ct_da_day':    ('Đã đối chiếu', 'ກວດສອບແລ້ວ', 'Reconciled'),
 'ct_danh_dau':  ('Đã đối chiếu ✓', 'ກວດສອບແລ້ວ ✓', 'Mark reconciled ✓'),
 'ct_mo_lai':    ('Mở lại', 'ເປີດຄືນ', 'Reopen'),
 'ct_doi_tuong': ('Đối tượng', 'ຄູ່ສັນຍາ', 'Party'),
 'ct_no_co':     ('Nợ / Có', 'ໜີ້ / ມີ', 'Debit / Credit'),
 'ct_so_to':     ('Số tờ', 'ຈຳນວນໃບ', 'Documents'),
 'ct_khong_co':  ('Chưa có chứng từ nào trong khoảng này', 'ຍັງບໍ່ມີເອກະສານໃນຊ່ວງນີ້', 'No documents in this range'),
 'ct_hint':      ('Mỗi bước nghiệp vụ bỏ vào đây một tờ. Bên kế toán kéo về để lập phiếu thu, phiếu chi, phiếu nhập kho, phiếu xuất kho; xong thì đánh dấu đã đối chiếu. Đây không phải sổ kế toán.',
                  'ແຕ່ລະຂັ້ນຕອນສ້າງເອກະສານໜຶ່ງໃບຢູ່ນີ້. ພະແນກບັນຊີດຶງໄປສ້າງໃບຮັບເງິນ, ໃບຈ່າຍເງິນ, ໃບຮັບເຂົ້າສາງ, ໃບເບີກອອກສາງ; ແລ້ວໝາຍວ່າກວດສອບແລ້ວ. ນີ້ບໍ່ແມ່ນປື້ມບັນຊີ.',
                  'Each step drops one document here. Accounting pulls them to create receipts, payments, stock-in and stock-out slips, then marks them reconciled. This is not the ledger.'),
 # ---- v6: khoá phiếu (bước 14) · đính kèm phiếu quặng · trả chủ xe liên kết · bán hàng
 'a_lock':        ('Khoá phiếu', 'ລັອກໃບ', 'Lock slip'),
 'a_unlock_slip': ('Mở khoá phiếu', 'ປົດລັອກໃບ', 'Unlock slip'),
 's_locked':      ('Đã khoá', 'ລັອກແລ້ວ', 'Locked'),
 'lock_warn':     ('Máy rà thấy các điểm sau. Đọc xong nếu vẫn đúng thì xác nhận khoá:', 'ລະບົບພົບຈຸດຕ່ອງໄປນີ້. ຖ້າຖືກຕ້ອງແລ້ວ ໃຫ້ຢືນຢັນລັອກ:', 'These points need a look. If they are right, confirm the lock:'),
 'lock_ok':       ('Phiếu không có điểm lệch. Khoá rồi Bãi không sửa được nữa.', 'ໃບບໍ່ມີຈຸດຜິດພາດ. ລັອກແລ້ວ ລານຈະແກ້ບໍ່ໄດ້ອີກ.', 'No discrepancies found. Once locked the yard cannot edit.'),
 'attach_ore':    ('Phiếu quặng đính kèm', 'ບິນແຮ່ຄັດຕິດ', 'Attached ore bill'),
 'attach_add':    ('Thêm ảnh · PDF', 'ເພີ່ມຮູບ · PDF', 'Add photo · PDF'),
 'attach_none':   ('Chưa đính kèm', 'ຍັງບໍ່ໄດ້ຄັດຕິດ', 'Nothing attached'),
 'attach_del':    ('Xoá tệp này khỏi phiếu?', 'ລຶບໄຟລ໌ນີ້ອອກຈາກໃບ?', 'Remove this file from the slip?'),
 'attach_after_save': ('Lưu phiếu rồi mới đính kèm được', 'ບັນທຶກໃບກ່ອນ ແລ້ວຈຶ່ງຄັດຕິດໄດ້', 'Save the slip first, then attach'),
 'pay_owner':     ('Trả chủ xe', 'ຈ່າຍເຈົ້າຂອງລົດ', 'Pay truck owner'),
 'owner_paid':    ('Đã trả chủ xe', 'ຈ່າຍເຈົ້າຂອງລົດແລ້ວ', 'Owner paid'),
 'owner_unpaid':  ('Chưa trả', 'ຍັງບໍ່ຈ່າຍ', 'Unpaid'),
 'owner_wait_lock': ('Chờ khoá phiếu', 'ລໍຖ້າລັອກໃບ', 'Waiting for lock'),
 'nav_sales':     ('Bán hàng', 'ຂາຍສິນຄ້າ', 'Sales'),
 'title_ban_hang': ('Bán hàng<span class="sub">Bán phụ tùng · xăng dầu cho bên ngoài</span>', 'ຂາຍສິນຄ້າ<span class="sub">ຂາຍອາໄຫຼ່ · ນໍ້າມັນ ໃຫ້ພາຍນອກ</span>', 'Sales<span class="sub">Spare parts · fuel sold to outside buyers</span>'),
 'sale_new':      ('Lập phiếu bán', 'ສ້າງໃບຂາຍ', 'New sale'),
 'sale_issue':    ('Lập phiếu · xuất kho', 'ສ້າງໃບ · ເບີກສາງ', 'Issue · stock out'),
 'sale_no':       ('Số phiếu bán', 'ເລກໃບຂາຍ', 'Sale no.'),
 'sale_lines':    ('Hàng bán', 'ສິນຄ້າ', 'Items'),
 'sale_hint':     ('Có trong kho thì xuất kho. Lập phiếu là có xuất kho và hoá đơn bán; thu tiền thì bấm Đã thu.', 'ມີໃນສາງແລ້ວເບີກອອກ. ສ້າງໃບແລ້ວມີໃບເບີກ ແລະ ໃບເກັບເງິນ; ຮັບເງິນແລ້ວກົດ ຮັບແລ້ວ.', 'Stock is issued on save. Saving creates the stock-out and the invoice; press Collected when paid.'),
 'sale_customer_free': ('Hoặc tên người mua', 'ຫຼື ຊື່ຜູ້ຊື້', 'Or buyer name'),
 'item_type':     ('Loại hàng', 'ປະເພດສິນຄ້າ', 'Type'),
 'it_part':       ('Phụ tùng', 'ອາໄຫຼ່', 'Spare part'),
 'it_fuel':       ('Dầu kho', 'ນໍ້າມັນສາງ', 'Fuel from store'),
 'sale_fuel_l':   ('số lượng tính bằng lít', 'ຈຳນວນເປັນລິດ', 'quantity in litres'),
 'sale_no_lines': ('Chưa có dòng nào — bấm + Phụ tùng hoặc + Dầu kho', 'ຍັງບໍ່ມີແຖວ — ກົດ + ອາໄຫຼ່ ຫຼື + ນໍ້າມັນສາງ', 'No lines yet — press + Spare part or + Fuel'),
 'sale_collect':  ('Đã thu', 'ຮັບເງິນແລ້ວ', 'Collected'),
 'sale_collect_hint': ('Ghi đã thu sẽ sinh phiếu thu bán hàng trong Sổ chứng từ.', 'ການບັນທຶກຮັບເງິນຈະສ້າງໃບຮັບເງິນຂາຍໃນປື້ມເອກະສານ.', 'Marking collected creates a sales receipt in the document register.'),
 'sale_delete_hint': ('Bỏ phiếu chưa thu: hàng trả về kho, tờ chứng từ chưa đối chiếu rút theo.', 'ຍົກເລີກໃບທີ່ຍັງບໍ່ຮັບເງິນ: ສິນຄ້າກັບຄືນສາງ, ເອກະສານທີ່ຍັງບໍ່ກວດຈະຖືກຖອນ.', 'Cancel an unpaid sale: stock returns, unreconciled documents are withdrawn.'),
 'sale_paid':     ('Đã thu', 'ຮັບເງິນແລ້ວ', 'Paid'),
 'sale_issued':   ('Chưa thu', 'ຍັງບໍ່ຮັບເງິນ', 'Unpaid'),
 'sale_unpaid':   ('Chưa thu', 'ຍັງບໍ່ຮັບ', 'Unpaid'),
 'by_user':       ('Người lập', 'ຜູ້ສ້າງ', 'Created by'),
 # nhãn nhật ký phiếu cho các bước mới (nhanLog tra thẳng bằng mã hành động)
 'a_lock_warn':   ('Khoá phiếu (có ghi nhận điểm lệch)', 'ລັອກໃບ (ມີຈຸດຕ່າງ)', 'Locked (with noted discrepancies)'),
 'a_attach':      ('Đính kèm tệp', 'ຄັດຕິດໄຟລ໌', 'Attached a file'),
 'a_detach':      ('Xoá tệp đính kèm', 'ລຶບໄຟລ໌ຄັດຕິດ', 'Removed an attachment'),
 'a_pay_owner':   ('Chi trả chủ xe liên kết', 'ຈ່າຍເຈົ້າຂອງລົດຮ່ວມ', 'Paid the truck owner'),
 # ---- v11: vai theo ĐÚNG bảng "Nhiệm Vụ" trong Excel của khách (anh chốt: "phải theo role của họ").
 #      KT Thu/Chi VC và KT Chi phí VC là hai người, hai vai. Tiếng Lào ráp từ nhãn bản mẫu đã có.
 'r_acct':      ('KT Thu/Chi Viêng Chăn', 'ບັນຊີລາຍຈ່າຍ/ຮັບ ວຽງຈັນ', 'Vientiane receipts & payments accountant'),
 'r_expacct':   ('KT Chi phí VC', 'ບັນຊີລາຍຈ່າຍ ວຽງຈັນ', 'Vientiane cost accountant'),
 'r_fuel':      ('KT kho xăng dầu VC', 'ບັນຊີສາງນໍ້າມັນ ວຽງຈັນ', 'Vientiane fuel store accountant'),
 'r_treasury':  ('Thủ quỹ VC', 'ຄັງເງິນ ວຽງຈັນ', 'Vientiane treasurer'),
 'r_cash':      ('Quỹ tiền mặt cảng cạn', 'ຄັງເງິນສົດຍ່ອຍ ການເງິນທ່າບົກ', 'Dry-port petty cash'),
 'r_rev':       ('KT Doanh thu VC', 'ບັນຊີລາຍຮັບ ວຽງຈັນ', 'Vientiane revenue accountant'),
 'hint_acct':   ('Vai trò <b>KT Thu/Chi Viêng Chăn</b>: xác nhận mục I và II. Không sửa số Bãi đã nhập; mục IV–VI thuộc KT Chi phí VC.',
                 '<b>ບັນຊີລາຍຈ່າຍ/ຮັບ ວຽງຈັນ</b>: ຢັ້ງຢືນໜ້າ I ແລະ II. ບໍ່ແກ້ຕັວເລກທີ່ສະໜາມລົງ; ໜ້າ IV–VI ແມ່ນຂອງບັນຊີລາຍຈ່າຍ.',
                 'Receipts & payments accountant: verify sections I and II. Yard figures cannot be edited; IV–VI belong to the cost accountant.'),
 'hint_expacct': ('Vai trò <b>KT Chi phí VC</b>: kiểm tra và ghi sổ mục IV, V, VI; theo dõi nhà cung cấp; chốt tất toán tài xế.',
                 '<b>ບັນຊີລາຍຈ່າຍ ວຽງຈັນ</b>: ກວດ ແລະ ບັນທຶກໜ້າ IV, V, VI; ຕິດຕາມຜູ້ສະໜອງ; ສະສາງໂຊເຟີ.',
                 'Cost accountant: verify and book sections IV, V, VI; suppliers; driver settlement.'),
 'hint_fuel':   ('Vai trò <b>KT kho xăng dầu VC</b>: kiểm và ghi sổ mục III, duyệt dầu tài xế đổ dọc đường.',
                 '<b>ບັນຊີສາງນໍ້າມັນ ວຽງຈັນ</b>: ກວດ ແລະ ບັນທຶກໜ້າ III, ອະນຸມັດນໍ້າມັນທີ່ໂຊເຟີເຕີມລະຫວ່າງທາງ.',
                 'Fuel store accountant: verify and book section III, approve roadside refuels.'),
 'hint_treasury': ('Vai trò <b>Thủ quỹ VC</b>: thanh toán mục III sau khi KT kho xăng dầu đã ghi sổ.',
                 '<b>ຄັງເງິນ ວຽງຈັນ</b>: ຈ່າຍໜ້າ III ຫຼັງບັນຊີສາງນໍ້າມັນບັນທຶກແລ້ວ.',
                 'Treasurer: pay section III after the fuel accountant has booked it.'),
 'hint_cash':   ('Vai trò <b>Quỹ tiền mặt cảng cạn</b>: thanh toán mục IV, V, VI đã ghi sổ; đánh dấu "Đã chi".',
                 '<b>ຄັງເງິນສົດຍ່ອຍ ທ່າບົກ</b>: ຈ່າຍໜ້າ IV, V, VI ທີ່ບັນທຶກແລ້ວ; ໝາຍ "ຈ່າຍແລ້ວ".',
                 'Dry-port petty cash: pay booked sections IV, V, VI; mark "Paid".'),
 # ---- v7: anh đổi tên hai vai. `yard` không gọi là "Bãi Thà Bốc" nữa mà là ADMIN THÀ BỐC (người
 # quản lý tại bãi, không phải cái bãi); `admin` gọi là SẾP cho đúng người dùng thật ở EPL.
 # Ghi đè ở đây chứ không sửa tu_dien_mau_vi_lo.json — tệp đó chép nguyên từ bản mẫu bên Lào.
 'r_yard':    ('Admin Thà Bốc', 'ແອັດມິນ ທ່າບົກ', 'Thabok admin'),
 'r_admin':   ('Sếp (xem tất cả)', 'ຫົວໜ້າ (ເບິ່ງທັງໝົດ)', 'Boss (sees all)'),
 'user_role': ('Admin Thà Bốc · Nhập liệu', 'ແອັດມິນ ທ່າບົກ · ລົງຂໍ້ມູນ', 'Thabok admin · Data entry'),
 'hint_yard': ('Anh/chị đang nhập với vai trò <b>Admin Thà Bốc</b>: được nhập mục I–VI. Kế toán và quỹ chỉ xem.',
               'ທ່ານກຳລັງລົງຂໍ້ມູນໃນນາມ <b>ແອັດມິນ ທ່າບົກ</b>: ລົງໄດ້ໜ້າ I–VI. ບັນຊີ ແລະ ຄັງເງິນ ເບິ່ງຢ່າງດຽວ.',
               'You are entering as Thabok admin: sections I–VI editable. Accounting and treasury view only.'),
 'hint_admin': ('Vai trò <b>Sếp</b>: xem và sửa tất cả.', '<b>ຫົວໜ້າ</b>: ເບິ່ງ ແລະ ແກ້ໄດ້ທັງໝົດ.', 'Boss: view and edit everything.'),
 # cùng tên vai ấy ở các chỗ khác: bước 1 trên phiếu, ô ký tên người lập, nhóm ở màn đăng nhập
 'wf1d':        ('Admin Thà Bốc', 'ແອັດມິນ ທ່າບົກ', 'Thabok admin'),
 'sg_issuer_d': ('Admin Thà Bốc', 'ແອັດມິນ ທ່າບົກ', 'Thabok admin'),
 'lg_yard':     ('Admin Thà Bốc (nhập liệu)', 'ແອັດມິນ ທ່າບົກ (ລົງຂໍ້ມູນ)', 'Thabok admin (entry)'),
 'lg_g_admin':  ('Sếp', 'ຫົວໜ້າ', 'Boss'),
 # ---- v8: hai kiểu xem điều hướng (thanh bên · thanh trên) + nhãn ngắn cho menu
 'brand_short':    ('Quản lý vận tải EPL', 'ຈັດການຂົນສົ່ງ EPL', 'EPL Transport Management'),
 'nav_search':     ('Tìm chức năng… (Ctrl K)', 'ຄົ້ນຫາໜ້າທີ່… (Ctrl K)', 'Find a screen… (Ctrl K)'),
 'nav_none':       ('Không có chức năng nào khớp', 'ບໍ່ມີໜ້າທີ່ກົງກັນ', 'No screen matches'),
 'nav_more':       ('Thêm', 'ເພີ່ມ', 'More'),
 'nav_collapse':   ('Thu gọn · mở rộng thanh bên', 'ຫຍໍ້ · ຂະຫຍາຍແຖບຂ້າງ', 'Collapse · expand sidebar'),
 'tab_transport':  ('Vận tải', 'ຂົນສົ່ງ', 'Transport'),
 'tab_warehouse':  ('Kho', 'ສາງ', 'Stores'),
 'tab_master':     ('Danh mục', 'ຂໍ້ມູນພື້ນຖານ', 'Master data'),
 'tab_system':     ('Hệ thống', 'ລະບົບ', 'System'),
 'nav_tracking_s': ('Theo dõi phiếu', 'ຕິດຕາມໃບ', 'Slip tracking'),
 'nav_bill_s':     ('Hoá đơn', 'ໃບເກັບເງິນ', 'Invoices'),
 'nav_driver_s':   ('Tiền chuyến & nước', 'ເງິນຖ້ຽວ & ນ້ຳ', 'Trip & water money'),
 'nav_supplier_s': ('Theo dõi NCC', 'ຕິດຕາມຜູ້ສະໜອງ', 'Suppliers'),
 'nav_place_s':    ('Điểm đổ dầu', 'ຈຸດເຕີມນ້ຳມັນ', 'Fuel points'),
 'nav_workflow_s': ('Quy trình', 'ຂັ້ນຕອນ', 'Workflow'),
 'view_settings':  ('Cài đặt giao diện', 'ຕັ້ງຄ່າໜ້າຈໍ', 'Display settings'),
 'view_side':      ('Thanh bên', 'ແຖບຂ້າງ', 'Sidebar'),
 'view_side_d':    ('Thấy hết chức năng cùng lúc, có số việc đang chờ cạnh từng mục.',
                    'ເຫັນທຸກໜ້າທີ່ພ້ອມກັນ, ມີຕົວເລກວຽກລໍຖ້າຢູ່ຂ້າງແຕ່ລະລາຍການ.',
                    'See every screen at once, with pending counts beside each item.'),
 'view_top':       ('Thanh trên', 'ແຖບເທິງ', 'Top bar'),
 'view_top_d':     ('Nhường trọn chiều ngang cho bảng — hợp bảng nhiều cột.',
                    'ໃຫ້ຄວາມກວ້າງທັງໝົດແກ່ຕາຕະລາງ — ເໝາະກັບຕາຕະລາງຫຼາຍຖັນ.',
                    'Gives the full width to tables — good for wide tables.'),
 'view_narrow':    ('Thanh bên chỉ hiện biểu tượng', 'ແຖບຂ້າງສະແດງແຕ່ໄອຄອນ', 'Icon-only sidebar'),
 # ---- v9: một câu nói mỗi màn làm gì, hiện dưới tên màn trong menu thả xuống của thanh trên
 'd_tong_quan':      ('Doanh thu, chi phí, việc cần xử lý', 'ລາຍຮັບ, ລາຍຈ່າຍ, ວຽກຕ້ອງເຮັດ', 'Revenue, costs, what needs attention'),
 'd_theo_doi':       ('Bảng phiếu vận chuyển theo tháng', 'ຕາຕະລາງໃບຂົນສົ່ງຕາມເດືອນ', 'Monthly table of transport slips'),
 'd_theo_doi_tuyen': ('Bản đồ GPS, chặng đã qua, sự cố', 'ແຜນທີ່ GPS, ຈຸດຜ່ານ, ເຫດການ', 'GPS map, stops reached, incidents'),
 'd_phieu_xuat_xe':  ('Lập và duyệt sáu mục của phiếu', 'ສ້າງ ແລະ ອະນຸມັດຫົກໜ້າຂອງໃບ', 'Create and approve the six sections'),
 'd_hoa_don':        ('Hoá đơn vận chuyển để in', 'ໃບເກັບເງິນຂົນສົ່ງເພື່ອພິມ', 'Printable transport invoice'),
 'd_chung_tu':       ('Phiếu chi, phiếu thu, sổ chứng từ', 'ໃບຈ່າຍ, ໃບຮັບ, ປື້ມເອກະສານ', 'Payment, receipt and the document register'),
 'd_phieu_cua_toi':  ('Phiếu của tài xế, khai dầu, vị trí', 'ໃບຂອງໂຊເຟີ, ແຈ້ງນ້ຳມັນ, ຕຳແໜ່ງ', "Driver's slips, fuel reports, location"),
 'd_cap_phat':       ('Quét QR, cấp dầu và chi tạm ứng', 'ສະແກນ QR, ຈ່າຍນ້ຳມັນ ແລະ ເງິນລ່ວງໜ້າ', 'Scan QR, issue fuel and advances'),
 'd_xe_lien_ket':    ('Tính tiền trả chủ xe thuê ngoài', 'ຄິດໄລ່ເງິນຈ່າຍເຈົ້າຂອງລົດຮ່ວມ', 'What to pay each joint-truck owner'),
 'd_tien_tai_xe':    ('Tiền chuyến và tiền nước theo tháng', 'ເງິນຖ້ຽວ ແລະ ເງິນນ້ຳຕາມເດືອນ', 'Monthly trip and water money'),
 'd_tat_toan':       ('Đối đã ứng với chi thật cuối tháng', 'ທຽບເງິນລ່ວງໜ້າກັບລາຍຈ່າຍຈິງທ້າຍເດືອນ', 'Advances against real spending, monthly'),
 'd_nha_cung_cap':   ('Công nợ nhà cung cấp, trả theo đợt', 'ໜີ້ຜູ້ສະໜອງ, ຈ່າຍເປັນງວດ', 'Supplier debt, paid in instalments'),
 'd_kho_nhien_lieu': ('Nhập, xuất, tồn dầu ở kho', 'ຮັບ, ເບີກ, ຍອດນ້ຳມັນໃນສາງ', 'Fuel in, out and balance'),
 'd_diem_do':        ('Kho dầu của EPL và trạm bên ngoài', 'ສາງນ້ຳມັນ EPL ແລະ ປ້ຳພາຍນອກ', 'EPL fuel stores and outside stations'),
 'd_kho_phu_tung':   ('Tồn phụ tùng và xuất theo xe', 'ຍອດອາໄຫຼ່ ແລະ ການເບີກຕາມລົດ', 'Parts stock and issues per truck'),
 'd_ban_hang':       ('Bán phụ tùng, xăng dầu cho bên ngoài', 'ຂາຍອາໄຫຼ່, ນ້ຳມັນ ໃຫ້ພາຍນອກ', 'Sell parts and fuel to outside buyers'),
 'd_khach_hang':     ('Danh mục khách nhận quặng', 'ບັນຊີລູກຄ້າຮັບແຮ່', 'Ore receiving customers'),
 'd_xe':             ('Đầu kéo, rơ-moóc, công-tơ-mét', 'ຫົວລາກ, ຫາງ, ເລກກົງເຕີ', 'Tractors, trailers, odometers'),
 'd_tai_xe':         ('Tài xế và bằng lái', 'ໂຊເຟີ ແລະ ໃບຂັບຂີ່', 'Drivers and licences'),
 'd_tuyen_duong':    ('Chặng, số km, phí cao tốc', 'ຈຸດຜ່ານ, ກິໂລແມັດ, ຄ່າທາງດ່ວນ', 'Stops, kilometres, toll'),
 'd_quy_trinh':      ('Ai làm bước nào, sinh chứng từ gì', 'ໃຜເຮັດຂັ້ນໃດ, ອອກເອກະສານໃດ', 'Who does what, which document each step makes'),
 'd_tai_khoan':      ('Người dùng và vai trò', 'ຜູ້ໃຊ້ ແລະ ໜ້າທີ່', 'Users and roles'),
 # ---- v10: màn Theo dõi tuyến dựng lại theo bản mẫu (ba cột, mốc chặng, ba tab, hồ sơ chuyến)
 'td_tile_hint':   ('Bấm để lọc danh sách', 'ກົດເພື່ອກັ່ນຕອງລາຍການ', 'Click to filter the list'),
 'td_docs':        ('Chứng từ', 'ເອກະສານ', 'Documents'),
 'td_route_total': ('Tổng tuyến', 'ລວມເສັ້ນທາງ', 'Route total'),
 'td_gone_km':     ('đã đi', 'ໄປແລ້ວ', 'covered'),
 'td_next_stop':   ('tiếp theo:', 'ຕໍ່ໄປ:', 'next:'),
 'td_done_route':  ('đã đi hết tuyến', 'ໄປຄົບເສັ້ນທາງແລ້ວ', 'route complete'),
 'td_ev_count':    ('{n} diễn biến', '{n} ເຫດການ', '{n} events'),
 'td_last_ev':     ('Gần nhất', 'ລ່າສຸດ', 'Latest'),
 'td_cost_note':   ('Ghi vào mục V của phiếu xuất xe', 'ລົງໃນໜ້າ V ຂອງໃບເບີກລົດ', 'Booked to section V of the slip'),
 'td_no_docs':     ('Chuyến này chưa có chứng từ nào', 'ຖ້ຽວນີ້ຍັງບໍ່ມີເອກະສານ', 'No documents for this trip yet'),
 'td_doc_count':   ('{n} chứng từ', '{n} ເອກະສານ', '{n} documents'),
 'td_doc_note':    ('Phiếu lĩnh · tạm ứng · tệp đính kèm · sổ chứng từ',
                    'ໃບເບີກ · ເງິນລ່ວງໜ້າ · ໄຟລ໌ຄັດຕິດ · ປື້ມເອກະສານ',
                    'Draw slips · advances · attachments · document register'),
 'td_fare_est':    ('Cước dự kiến', 'ຄ່າຂົນສົ່ງຄາດຄະເນ', 'Expected freight'),
 'td_unpaid_amt':  ('Chưa thu', 'ຍັງບໍ່ໄດ້ຮັບ', 'Unpaid'),
 'td_paid_full':   ('Đã thu đủ', 'ຮັບຄົບແລ້ວ', 'Fully collected'),
 'td_confirm_stop': ('Xác nhận tới điểm {n}', 'ຢືນຢັນຮອດຈຸດ {n}', 'Confirm arrival at stop {n}'),
 'td_issue_fuel':  ('Cấp phiếu lĩnh nhiên liệu', 'ຈ່າຍໃບເບີກນໍ້າມັນ', 'Issue the fuel draw slip'),
 'td_days':        ('Số ngày đi', 'ຈຳນວນວັນ', 'Days out'),
 'td_days_n':      ('{n} ngày', '{n} ວັນ', '{n} days'),
 'td_legs_short':  ('Chặng · km', 'ຈຸດ · ກມ', 'Stops · km'),
 # ---- v12: màn phiếu xuất xe dạng tab theo vai
 'px_tab_all':     ('Toàn phiếu', 'ໃບເຕັມ', 'Whole slip'),
 # ---- v13: bảng giá khách × tuyến (K3)
 'kh_bang_gia':    ('Bảng giá', 'ຕາຕະລາງລາຄາ', 'Price list'),
 'kh_gia_cua':     ('Bảng giá · {n}', 'ຕາຕະລາງລາຄາ · {n}', 'Price list · {n}'),
 'kh_gia_mota':    ('Giá hợp đồng theo tuyến (USD/tấn). Mở phiếu chọn khách và tuyến là tự điền; kế toán chỉ sửa trên phiếu khi chuyến đó khác hợp đồng.',
                    'ລາຄາສັນຍາຕາມເສັ້ນທາງ (USD/ໂຕນ). ເປີດໃບເລືອກລູກຄ້າ ແລະ ເສັ້ນທາງ ລາຄາຈະຕື່ມເອງ; ບັນຊີແກ້ໃນໃບສະເພາະຖ້ຽວທີ່ຕ່າງຈາກສັນຍາ.',
                    'Contract rate per route (USD/t). When a slip has a customer and a route the rate is filled in automatically; accounting edits it on the slip only when that trip differs from the contract.'),
 'kh_gia_trong':   ('Chưa có giá cho khách này. Thêm giá theo tuyến để phiếu tự điền đơn giá.', 'ຍັງບໍ່ມີລາຄາສຳລັບລູກຄ້ານີ້. ເພີ່ມລາຄາຕາມເສັ້ນທາງ ເພື່ອໃຫ້ໃບຕື່ມລາຄາເອງ.', 'No rates for this customer yet. Add a rate per route so slips fill the price automatically.'),
 'valid_from':     ('Áp dụng từ', 'ນຳໃຊ້ຕັ້ງແຕ່', 'Valid from'),
 'px_gia_tu_bang': ('Đã điền đơn giá theo bảng giá khách × tuyến', 'ຕື່ມລາຄາຕາມຕາຕະລາງລາຄາ ລູກຄ້າ × ເສັ້ນທາງ ແລ້ວ', 'Rate filled from the customer × route price list'),
 'close':          ('Đóng', 'ປິດ', 'Close'),
 # ---- v14: Tổng quan cho vai Bãi (không có tiền)
 'k_month_trips':  ('Phiếu tháng này', 'ໃບເບີກລົດເດືອນນີ້', 'Slips this month'),
 'k_running':      ('Xe đang trên đường', 'ລົດກຳລັງເດີນທາງ', 'Trucks on the road'),
 'k_todo':         ('Việc cần xử lý', 'ວຽກທີ່ຕ້ອງເຮັດ', 'Things to handle'),
 'k_todo_u':       ('việc', 'ວຽກ', 'items'),
 'k_todo_s':       ('Xem cột bên phải', 'ເບິ່ງຖັນຂວາ', 'See the list on the right'),
 'td_hide_profile': ('Thu thanh xem nhanh', 'ຫຍໍ້ແຖບເບິ່ງດ່ວນ', 'Hide the quick view'),
 'td_paid_part':   ('Thu một phần', 'ຮັບບາງສ່ວນ', 'Partly collected'),
}
# alias vai — cùng chữ với khoá đã có
ALIAS = {}   # nhãn vai nay ghi thẳng trong KHOA_MOI theo đúng chữ bảng Nhiệm Vụ của khách

thieu = [k for k in T if k not in EN]
assert not thieu, 'thieu EN cho: %s' % thieu

ra = {}
for k, (vi, lo) in T.items():
    ra[k] = {'vi': vi, 'lo': lo, 'en': EN[k]}
for k, v in KHOA_MOI.items():
    if v is None:
        continue
    ra[k] = {'vi': v[0], 'lo': v[1], 'en': v[2]}
for k, goc in ALIAS.items():
    ra[k] = dict(ra[goc])
# tiêu đề module theo id mới ← tiêu đề cũ của bản mẫu
for moi, cu in (('title_tong_quan', 'title_dashboard'), ('title_theo_doi', 'title_tracking'),
                ('title_phieu_xuat_xe', 'title_dispatch'), ('title_hoa_don', 'title_bill'),
                ('title_xe_lien_ket', 'title_joint'), ('title_tien_tai_xe', 'title_driver'),
                ('title_nha_cung_cap', 'title_supplier'), ('title_kho_nhien_lieu', 'title_fuel'),
                ('title_kho_phu_tung', 'title_parts'), ('title_quy_trinh', 'title_workflow')):
    ra[moi] = dict(ra[cu])
# tiêu đề tổng quan không ghim tháng 8/2026 nữa — tháng lấy theo bộ lọc
ra['title_tong_quan'] = {'vi': 'Tổng quan<span class="sub">Theo tháng · Công ty EPL</span>',
                         'lo': 'ພາບລວມ<span class="sub">ຕາມເດືອນ · ບໍລິສັດ EPL</span>',
                         'en': 'Overview<span class="sub">Monthly · EPL company</span>'}

dau = ('/* Từ điển ba ngôn ngữ của EPL Lào — SINH TỰ ĐỘNG bởi sinh_ngon_ngu.py, đừng sửa tay.\n'
       ' * vi/lo chép nguyên từ bản giao diện mẫu bên Lào đã duyệt; en thêm sau.\n'
       ' * Chế độ "VI + ລາວ" do js/chung.js ghép từ vi và lo. Tổng %d khoá. */\n' % len(ra))
noi_dung = dau + 'window.EPL_TU_DIEN = ' + json.dumps(ra, ensure_ascii=False, indent=1) + ';\n'
io.open(DICH, 'w', encoding='utf-8', newline='\n').write(noi_dung)
print('Đã sinh %s · %d khoá' % (DICH, len(ra)))
