# -*- coding: utf-8 -*-
"""Bộ câu hỏi kiểm thử EPL Trợ lý — MỘT câu hỏi, BA ngôn ngữ.

Mỗi mục: (mã, nhóm, công cụ mong đợi, câu hỏi VI, câu hỏi EN, câu hỏi LO, cần thấy gì).

Nguyên tắc soạn:
  · Phủ hết 21 công cụ. Công cụ nào không có câu hỏi nào chạm tới là một mảng chưa ai thử.
  · Mỗi câu có "cần thấy gì" ĐO ĐƯỢC — người kiểm đối chiếu được với màn hình gốc, chứ không
    phải "trả lời hợp lý là đạt".
  · Ba ngôn ngữ là BA BẢN DỊCH TRỌN của cùng một câu, không phải ba câu khác nhau. Đổi ngôn
    ngữ trên trang rồi hỏi lại đúng câu đó thì phải ra cùng một con số.
  · Có cả câu PHẢI BỊ TỪ CHỐI (nhóm K) — bản này chỉ đọc, và ranh giới đó phải kiểm được.
"""

# (ma, nhom, cong_cu, vi, en, lo, can_thay)
CAU_HOI = [
    # ---------------------------------------------------------------- A. Mở màn
    ("A1", "Tổng quan", "tong_quan_hom_nay",
     "Hôm nay có gì cần lo không?",
     "Anything I should worry about today?",
     "ມື້ນີ້ມີຫຍັງຕ້ອງກັງວົນບໍ?",
     "Nêu được sự cố đang mở, lệnh quá hạn/gần trễ, xe và tài xế rảnh, giấy tờ sắp hết hạn."),
    ("A2", "Tổng quan", "tong_quan_hom_nay",
     "Tóm tắt tình hình vận hành hôm nay cho anh.",
     "Give me a summary of today's operations.",
     "ສະຫຼຸບສະພາບການດຳເນີນງານມື້ນີ້ໃຫ້ແດ່.",
     "Một đoạn ngắn có số liệu, không dài dòng, có mã lệnh để tra lại."),
    ("A3", "Tổng quan", "tong_quan_hom_nay · phan_tich_lenh_giao_hang",
     "Có bao nhiêu lệnh giao hàng đang chạy và bao nhiêu đã hoàn tất?",
     "How many delivery orders are in transit and how many are completed?",
     "ມີ DO ຈັກໃບກຳລັງຂົນສົ່ງ ແລະ ຈັກໃບສຳເລັດແລ້ວ?",
     "Hai con số khớp ĐÚNG ô 'Đang vận chuyển' và 'Hoàn thành' trên bảng Phân tích lệnh giao "
     "hàng. Đây là câu bẫy: đếm thô theo trạng thái sẽ ra số khác (gộp cả lệnh đã tới chờ ký)."),
    ("A4", "Tổng quan", "tong_quan_hom_nay",
     "Việc gì gấp nhất bây giờ?",
     "What is the most urgent thing right now?",
     "ຫຍັງດ່ວນທີ່ສຸດຕອນນີ້?",
     "Chọn ra được việc gấp (quá hạn / sự cố High) chứ không liệt kê lại tất cả."),
    ("A5", "Tổng quan", "su_co · nguon_luc_doi_xe",
     "Hôm nay có hư hỏng gì không?",
     "Any breakdowns today?",
     "ມື້ນີ້ມີການເສຍຫາຍຫຍັງບໍ?",
     "Nêu sự cố loại hỏng hóc/hàng hư hỏng kèm xe và mã lệnh."),

    # ---------------------------------------------------------------- B. Lệnh giao hàng
    ("B1", "Lệnh giao hàng", "phan_tich_lenh_giao_hang · lenh_giao_hang",
     "Có lệnh nào quá hạn không, của khách nào?",
     "Are any orders overdue, and for which customer?",
     "ມີ DO ໃດເກີນກຳນົດບໍ, ຂອງລູກຄ້າໃດ?",
     "Đúng mã lệnh VÀ đúng tên khách (số ngày 12/09 là 2 lệnh DO-2026-0026, khách Samsung Electronics HCMC CE — dữ liệu làm tươi mỗi buổi, hãy đối chiếu màn hình). "
     "Tên khách sai là LỖI NẶNG — xem mục 6.2 của tài liệu."),
    ("B2", "Lệnh giao hàng", "phan_tich_lenh_giao_hang",
     "Lệnh nào sắp trễ trong 24 giờ tới?",
     "Which orders are about to be late within the next 24 hours?",
     "DO ໃດໃກ້ຊ້າພາຍໃນ 24 ຊົ່ວໂມງ?",
     "Nhóm Gần trễ, kèm mã lệnh và hạn giao (số ngày 12/09 là 1 lệnh — dữ liệu làm tươi mỗi buổi, hãy đối chiếu màn hình)."),
    ("B3", "Lệnh giao hàng", "phan_tich_lenh_giao_hang",
     "Còn bao nhiêu lệnh chờ điều phối xe?",
     "How many orders are still waiting for a vehicle?",
     "ຍັງມີ DO ຈັກໃບລໍຖ້າຈັດລົດ?",
     "Con số khớp ĐÚNG ô 'Chờ vận chuyển' trên bảng. Bẫy: đếm thô trạng thái pending sẽ cao hơn, "
     "vì bảng đã tách các lệnh quá hạn và gần trễ ra khỏi ô này."),
    ("B4", "Lệnh giao hàng", "theo_doi_lenh",
     "Cho anh xem chi tiết lệnh DO-2026-0050-DO01.",
     "Show me the details of order DO-2026-0050-DO01.",
     "ຂໍເບິ່ງລາຍລະອຽດ DO-2026-0050-DO01.",
     "Khách Vinamilk, tuyến Sóng Thần → Cảng Cát Lái, giá 1.406.000 VNĐ, xe DEMO-61H-888.02."),
    ("B5", "Lệnh giao hàng", "theo_doi_lenh",
     "Lệnh DO-2026-0050-DO01 đang ở đâu, bao giờ tới?",
     "Where is order DO-2026-0050-DO01 now, and when will it arrive?",
     "DO-2026-0050-DO01 ຢູ່ໃສແລ້ວ, ຈະຮອດເມື່ອໃດ?",
     "Trạng thái đang vận chuyển, mốc kế tiếp, và nói rõ GPS là vị trí mô phỏng nếu đúng vậy."),
    ("B6", "Lệnh giao hàng", "lenh_giao_hang",
     "Những lệnh nào chưa có xe và tài xế?",
     "Which orders have no vehicle and driver assigned yet?",
     "DO ໃດຍັງບໍ່ມີລົດ ແລະ ຄົນຂັບ?",
     "Danh sách lệnh trạng thái chờ điều phối, không lẫn lệnh đã có xe."),
    ("B7", "Lệnh giao hàng", "lenh_giao_hang",
     "Lệnh giao hàng của Vinamilk có những cái nào?",
     "Which delivery orders belong to Vinamilk?",
     "DO ໃດແດ່ເປັນຂອງ Vinamilk?",
     "Tìm được theo TÊN khách (không phải mã khách), kèm trạng thái từng lệnh."),
    ("B8", "Lệnh giao hàng", "phan_tich_lenh_giao_hang · su_co",
     "Lệnh nào đang gặp sự cố?",
     "Which orders currently have an incident?",
     "DO ໃດກຳລັງມີເຫດການ?",
     "5 mã lệnh khớp nhóm Gặp sự cố, mỗi lệnh kèm loại sự cố."),

    # ---------------------------------------------------------------- C. Chuyến và theo dõi
    ("C1", "Chuyến", "chuyen_dang_chay · xe",
     "Xe nào đang trên đường?",
     "Which vehicles are on the road right now?",
     "ລົດຄັນໃດກຳລັງເດີນທາງຢູ່?",
     "Danh sách chuyến đang chạy kèm biển số, tài xế, tuyến. Số xe khớp ô 'vehicles' của Tháp "
     "kiểm soát; một xe có thể chở nhiều lệnh nên số dòng lớn hơn số xe."),
    ("C2", "Chuyến", "chuyen_dang_chay",
     "Chuyến nào đang trễ hạn giao?",
     "Which trips are past their delivery deadline?",
     "ຖ້ຽວໃດເກີນກຳນົດສົ່ງແລ້ວ?",
     "Chỉ lấy chuyến trễ; không trễ cái nào thì nói rõ 'không có', không bịa."),
    ("C3", "Chuyến", "chuyen_dang_chay",
     "Chuyến nào đã tới nơi mà chưa ký nhận POD?",
     "Which trips have arrived but are still waiting for the POD signature?",
     "ຖ້ຽວໃດມາຮອດແລ້ວແຕ່ຍັງບໍ່ໄດ້ເຊັນ POD?",
     "Đúng số chuyến chờ ký (số ngày 12/09 là 5 — dữ liệu làm tươi mỗi buổi, hãy đối chiếu màn hình), kèm tài xế và khách."),
    ("C4", "Chuyến", "chuyen_dang_chay",
     "Tài xế Somsak đang chở gì?",
     "What is driver Somsak carrying right now?",
     "ຄົນຂັບ Somsak ກຳລັງບັນທຸກຫຍັງ?",
     "Hai lệnh DO-2026-0050-DO01 (Vinamilk) và DO-2026-0051-DO01 (Acecook), cùng chuyến TRIP-TAIXE-DEMO-01."),
    ("C5", "Chuyến", "chuyen_dang_chay · chuyen",
     "Chuyến TRIP-TAIXE-DEMO-01 chở mấy lệnh, mốc kế tiếp là gì?",
     "How many orders is trip TRIP-TAIXE-DEMO-01 carrying, and what is the next milestone?",
     "ຖ້ຽວ TRIP-TAIXE-DEMO-01 ບັນທຸກຈັກ DO, ຂັ້ນຕອນຕໍ່ໄປແມ່ນຫຍັງ?",
     "2 lệnh; mốc kế tiếp đúng thứ tự sáu mốc (Đến điểm giao nếu chưa ghi thêm)."),
    ("C6", "Chuyến", "chuyen_dang_chay",
     "Có chuyến nào lệch tuyến không?",
     "Are any trips deviating from their route?",
     "ມີຖ້ຽວໃດອອກນອກເສັ້ນທາງບໍ?",
     "Đọc được độ lệch km; không có thì nói không có."),
    ("C7", "Chuyến", "chuyen_dang_chay · chuyen · xe",
     "Xe DEMO-61H-888.02 đang chạy chuyến nào?",
     "Which trip is vehicle DEMO-61H-888.02 running?",
     "ລົດ DEMO-61H-888.02 ກຳລັງແລ່ນຖ້ຽວໃດ?",
     "TRIP-TAIXE-DEMO-01, tài xế Somsak Phommachanh."),

    # ---------------------------------------------------------------- D. Sự cố
    ("D1", "Sự cố", "su_co",
     "Có sự cố nào đang mở không?",
     "Are there any open incidents?",
     "ມີເຫດການໃດຍັງເປີດຢູ່ບໍ?",
     "5 sự cố (số của ngày 12/09; đối chiếu màn hình chứ đừng chấm theo con số này) kèm loại, mức độ, vị trí, mã lệnh, xe."),
    ("D2", "Sự cố", "su_co",
     "Sự cố nào nghiêm trọng nhất?",
     "Which incident is the most severe?",
     "ເຫດການໃດຮ້າຍແຮງທີ່ສຸດ?",
     "Chọn mức High và nói rõ vì sao, không liệt kê lại cả năm."),
    ("D3", "Sự cố", "su_co",
     "Sự cố hàng hoá hư hỏng xảy ra ở đâu, xe nào?",
     "Where did the cargo-damage incident happen, and on which vehicle?",
     "ເຫດການສິນຄ້າເສຍຫາຍເກີດຢູ່ໃສ, ລົດຄັນໃດ?",
     "Kho Long An, xe DEMO-51C-412.09, lệnh DO-2026-0042-DO01, mức High."),
    ("D4", "Sự cố", "su_co",
     "Có bao nhiêu sự cố đã xử lý xong?",
     "How many incidents have been resolved?",
     "ມີເຫດການຈັກອັນທີ່ແກ້ໄຂແລ້ວ?",
     "Phân biệt được đang mở và đã đóng."),

    # ---------------------------------------------------------------- E. Báo giá
    ("E1", "Báo giá", "bao_gia · tong_quan_hom_nay",
     "Có bao nhiêu báo giá đang mở?",
     "How many quotations are still open?",
     "ມີໃບສະເໜີລາຄາຈັກໃບຍັງເປີດຢູ່?",
     "Khớp tóm lược báo giá (số ngày 12/09 là 56 đang mở — dữ liệu làm tươi mỗi buổi, hãy đối chiếu màn hình)."),
    ("E2", "Báo giá", "bao_gia",
     "Báo giá nào đang chờ khách phản hồi?",
     "Which quotations are waiting for the customer's reply?",
     "ໃບສະເໜີລາຄາໃດລໍຖ້າລູກຄ້າຕອບ?",
     "Trạng thái đã gửi khách (số ngày 12/09 là 9 — dữ liệu làm tươi mỗi buổi, hãy đối chiếu màn hình), kèm mã và khách."),
    ("E3", "Báo giá", "bao_gia",
     "Báo giá nào sắp hết hạn trong 7 ngày tới?",
     "Which quotations expire within the next 7 days?",
     "ໃບສະເໜີລາຄາໃດຈະໝົດອາຍຸພາຍໃນ 7 ມື້?",
     "Không có thì nói rõ 'không có', KHÔNG được báo lỗi kỹ thuật."),
    ("E4", "Báo giá", "bao_gia",
     "Báo giá nào có biên lợi nhuận dưới ngưỡng công ty?",
     "Which quotations have a margin below the company threshold?",
     "ໃບສະເໜີລາຄາໃດມີອັດຕາກຳໄລຕ່ຳກວ່າເກນບໍລິສັດ?",
     "Đọc được ngưỡng (15%) và đếm đúng (số ngày 12/09 là 4 — dữ liệu làm tươi mỗi buổi, hãy đối chiếu màn hình)."),
    ("E5", "Báo giá", "bao_gia",
     "Báo giá bằng Lào Kip có những cái nào, giá bao nhiêu?",
     "Which quotations are in Lao kip, and what are their prices?",
     "ໃບສະເໜີລາຄາໃດເປັນເງິນກີບລາວ, ລາຄາເທົ່າໃດ?",
     "Chỉ ra báo giá LAK và ghi rõ đơn vị LAK — KHÔNG quy đổi sang VNĐ."),
    ("E6", "Báo giá", "bao_gia",
     "Báo giá nào có biên lợi nhuận cao nhất?",
     "Which quotation has the highest profit margin?",
     "ໃບສະເໜີລາຄາໃດມີອັດຕາກຳໄລສູງສຸດ?",
     "Biên viết dạng phần trăm (34%), không để 0.34."),
    ("E7", "Báo giá", "bao_gia",
     "Tỉ lệ chốt báo giá 30 ngày qua là bao nhiêu?",
     "What is the win rate on quotations over the past 30 days?",
     "ອັດຕາປິດການຂາຍ 30 ມື້ຜ່ານມາເທົ່າໃດ?",
     "91,3% (số của ngày 12/09; đối chiếu màn hình chứ đừng chấm theo con số này) — dạng phần trăm, không phải 0.913."),
    ("E8", "Báo giá", "bao_gia",
     "Cho anh xem báo giá của Samsung.",
     "Show me Samsung's quotations.",
     "ຂໍເບິ່ງໃບສະເໜີລາຄາຂອງ Samsung.",
     "Tìm theo tên khách, mỗi dòng có tiền tệ riêng của phiếu."),

    # ---------------------------------------------------------------- F. Cơ hội và khách hàng
    ("F1", "Cơ hội", "co_hoi",
     "Có bao nhiêu cơ hội đang mở, ở giai đoạn nào?",
     "How many opportunities are open, and at which stage?",
     "ມີໂອກາດຈັກອັນຍັງເປີດ, ຢູ່ຂັ້ນຕອນໃດ?",
     "19 đang mở (số của ngày 12/09; đối chiếu màn hình chứ đừng chấm theo con số này), chia theo sáu giai đoạn, dùng tên giai đoạn tiếng Việt."),
    ("F2", "Cơ hội", "co_hoi",
     "Cơ hội nào đã báo giá mà khách chưa trả lời?",
     "Which opportunities have been quoted but the customer has not replied?",
     "ໂອກາດໃດສະເໜີລາຄາແລ້ວແຕ່ລູກຄ້າຍັງບໍ່ຕອບ?",
     "Giai đoạn Đã báo giá (số ngày 12/09 là 14 — dữ liệu làm tươi mỗi buổi, hãy đối chiếu màn hình), kèm khách và mã báo giá."),
    ("F3", "Cơ hội", "co_hoi",
     "Cơ hội nào bị mất và vì sao?",
     "Which opportunities were lost, and why?",
     "ໂອກາດໃດເສຍໄປ ແລະ ຍ້ອນຫຍັງ?",
     "Đọc được lý do mất (bắt buộc khi chọn Mất)."),
    ("F4", "Khách hàng", "doanh_thu · khach_hang",
     "Khách hàng nào có doanh thu cao nhất?",
     "Which customer brings the highest revenue?",
     "ລູກຄ້າໃດມີລາຍຮັບສູງສຸດ?",
     "Số tiền kèm mã tiền tệ; nêu tên khách cụ thể."),
    ("F5", "Khách hàng", "ho_so_khach_hang",
     "Cho anh hồ sơ khách hàng Vinamilk.",
     "Give me the customer profile for Vinamilk.",
     "ຂໍໂປຣໄຟລ໌ລູກຄ້າ Vinamilk.",
     "Cơ hội, báo giá, lệnh giao hàng, doanh thu của riêng khách đó."),
    ("F6", "Khách hàng", "khach_hang",
     "Có bao nhiêu khách hàng trong hệ thống?",
     "How many customers are in the system?",
     "ມີລູກຄ້າຈັກລາຍໃນລະບົບ?",
     "15 (số của ngày 12/09; đối chiếu màn hình chứ đừng chấm theo con số này)."),
    ("F7", "Khách hàng", "khach_hang · lenh_giao_hang",
     "Khách nào đang có nhiều lệnh đang chạy nhất?",
     "Which customer has the most orders in transit?",
     "ລູກຄ້າໃດມີ DO ກຳລັງຂົນສົ່ງຫຼາຍທີ່ສຸດ?",
     "Đếm đúng, không đếm trên trích đoạn cũ."),

    # ---------------------------------------------------------------- G. Đội xe, tài xế, lịch
    ("G1", "Đội xe", "nguon_luc_doi_xe · xe · tai_xe",
     "Xe và tài xế nào đang rảnh?",
     "Which vehicles and drivers are free?",
     "ລົດ ແລະ ຄົນຂັບຄັນໃດຫວ່າງ?",
     "Ngày 12/09 là: 0 xe rảnh, 4 tài xế rảnh — nói thẳng 0 xe, không né."),
    ("G2", "Đội xe", "nguon_luc_doi_xe",
     "Giấy tờ xe nào sắp hết hạn?",
     "Which vehicle documents are expiring soon?",
     "ເອກະສານລົດໃດໃກ້ໝົດອາຍຸ?",
     "3 xe (số của ngày 12/09; đối chiếu màn hình chứ đừng chấm theo con số này) kèm biển số, ngày hết hạn, còn mấy ngày."),
    ("G3", "Đội xe", "nguon_luc_doi_xe",
     "Bằng lái nào sắp hết hạn?",
     "Which driving licences are expiring soon?",
     "ໃບຂັບຂີ່ໃດໃກ້ໝົດອາຍຸ?",
     "DEMO-DRV-001 Nguyễn Văn Minh, hết hạn 25/09/2026."),
    ("G4", "Đội xe", "xe",
     "Có xe nào đang nằm xưởng không?",
     "Are any vehicles in the workshop?",
     "ມີລົດຄັນໃດຢູ່ອູ່ສ້ອມບໍ?",
     "Ngày 12/09 là: 0 — phải nói không có, không bịa ra xe."),
    ("G5", "Tài xế", "tai_xe",
     "Tài xế DEMO-DRV-015 là ai, hạng bằng gì?",
     "Who is driver DEMO-DRV-015, and what licence class?",
     "ຄົນຂັບ DEMO-DRV-015 ແມ່ນໃຜ, ໃບຂັບຂີ່ປະເພດໃດ?",
     "Somsak Phommachanh, lái xe chính, hạng FC, đang chạy TRIP-TAIXE-DEMO-01."),
    ("G6", "Đội xe", "xe",
     "Xe DEMO-61H-888.02 chở được bao nhiêu tấn?",
     "What is the payload capacity of vehicle DEMO-61H-888.02?",
     "ລົດ DEMO-61H-888.02 ບັນທຸກໄດ້ຈັກໂຕນ?",
     "15 tấn (15.000 kg), loại Xe tải thùng 15 tấn."),
    ("G7", "Đội xe", "bao_duong",
     "Tuần này có lịch bảo dưỡng xe nào không?",
     "Any vehicle maintenance scheduled this week?",
     "ອາທິດນີ້ມີກຳນົດບຳລຸງຮັກສາລົດຄັນໃດບໍ?",
     "Tự tính khoảng ngày của 'tuần này' rồi tra, không hỏi lại anh ngày nào."),
    ("G8", "Tài xế", "lich_tai_xe",
     "Tài xế nào có ca làm việc hôm nay?",
     "Which drivers are on shift today?",
     "ຄົນຂັບໃດມີກະວຽກມື້ນີ້?",
     "Danh sách ca phủ ngày hôm nay, kèm giờ."),

    # ---------------------------------------------------------------- H. Tuyến và tỷ giá
    ("H1", "Tuyến", "tuyen_duong",
     "Hệ thống có bao nhiêu tuyến đường?",
     "How many routes are in the system?",
     "ລະບົບມີເສັ້ນທາງຈັກເສັ້ນ?",
     "8 tuyến (số của ngày 12/09; đối chiếu màn hình chứ đừng chấm theo con số này)."),
    ("H2", "Tuyến", "tuyen_duong",
     "Tuyến Viêng Chăn đi Cảng Cửa Lò dài bao nhiêu km, qua mấy chặng?",
     "How long is the Vientiane to Cua Lo Port route, and how many legs?",
     "ເສັ້ນທາງວຽງຈັນໄປທ່າເຮືອກົວໂລ ໄກເທົ່າໃດ, ຜ່ານຈັກຊ່ວງ?",
     "Đúng km và liệt kê từng chặng theo thứ tự."),
    ("H3", "Tỷ giá", "ty_gia",
     "Tỷ giá Lào Kip sang VNĐ hiện là bao nhiêu?",
     "What is the current Lao kip to VND exchange rate?",
     "ອັດຕາແລກປ່ຽນກີບລາວເປັນ VNĐ ຕອນນີ້ເທົ່າໃດ?",
     "1 LAK = 1,18 VNĐ (số của ngày 12/09; đối chiếu màn hình chứ đừng chấm theo con số này), nói rõ chiều quy đổi."),
    ("H4", "Tuyến", "tuyen_duong",
     "Tuyến nào dài nhất?",
     "Which route is the longest?",
     "ເສັ້ນທາງໃດໄກທີ່ສຸດ?",
     "So được km giữa các tuyến."),

    # ---------------------------------------------------------------- I. Tiền, doanh thu, hoàn tất
    ("I1", "Doanh thu", "doanh_thu",
     "Doanh thu vận tải tháng này là bao nhiêu?",
     "What is this month's transport revenue?",
     "ລາຍຮັບການຂົນສົ່ງເດືອນນີ້ເທົ່າໃດ?",
     "Tự tính khoảng ngày đầu–cuối tháng; số tiền kèm mã tiền tệ."),
    ("I2", "Doanh thu", "doanh_thu",
     "Tuyến nào có lợi nhuận cao nhất?",
     "Which route is the most profitable?",
     "ເສັ້ນທາງໃດມີກຳໄລສູງສຸດ?",
     "Lợi nhuận theo tuyến, kèm biên phần trăm."),
    ("I3", "Hoàn tất", "ho_so_hoan_tat",
     "Có bao nhiêu hồ sơ đã hoàn tất chờ bàn giao kế toán?",
     "How many completed records are ready to hand over to accounting?",
     "ມີບັນທຶກສຳເລັດຈັກອັນລໍຖ້າສົ່ງມອບບັນຊີ?",
     "21 (số của ngày 12/09; đối chiếu màn hình chứ đừng chấm theo con số này)."),
    ("I4", "Hoàn tất", "chi_tiet_hoan_tat",
     "Cho anh chi tiết hồ sơ hoàn tất của lệnh DO-2026-0047-DO01.",
     "Show me the completion record for order DO-2026-0047-DO01.",
     "ຂໍລາຍລະອຽດບັນທຶກສຳເລັດຂອງ DO-2026-0047-DO01.",
     "Giá cuối, phụ phí khách trả, giá thành, lợi nhuận, và các khoản có Acc code."),
    ("I5", "Hoàn tất", "doanh_thu · ho_so_hoan_tat · chi_tiet_hoan_tat",
     "Lệnh nào có lợi nhuận thấp nhất?",
     "Which order had the lowest profit?",
     "DO ໃດມີກຳໄລຕ່ຳສຸດ?",
     "So sánh trên hồ sơ đã chốt, không đoán từ báo giá."),
    ("I6", "Doanh thu", "doanh_thu",
     "Doanh thu theo khách hàng trong tháng này?",
     "Revenue by customer for this month?",
     "ລາຍຮັບຕາມລູກຄ້າໃນເດືອນນີ້?",
     "Bảng khách – doanh thu, mỗi dòng kèm tiền tệ."),
    ("I7", "Hoàn tất", "ho_so_hoan_tat",
     "Có hồ sơ nào lệch giữa giá báo và giá chốt không?",
     "Are there records where the quoted price differs from the final price?",
     "ມີບັນທຶກໃດລາຄາສະເໜີຕ່າງຈາກລາຄາສຸດທ້າຍບໍ?",
     "Chỉ ra chênh lệch do phụ phí khách trả, không gọi là sai sót."),

    # ---------------------------------------------------------------- J. Trí nhớ hội thoại
    ("J1", "Trí nhớ", "(không gọi — trả lời từ trí nhớ)",
     "[Hỏi ngay sau A1] Cái sự cố hàng hư hỏng đó ở xe nào, mức độ gì?",
     "[Ask right after A1] That cargo-damage incident — which vehicle, and how severe?",
     "[ຖາມຕໍ່ຈາກ A1] ເຫດການສິນຄ້າເສຍຫາຍນັ້ນຢູ່ລົດຄັນໃດ, ຮ້າຍແຮງລະດັບໃດ?",
     "Trả lời trong khoảng 2–3 giây, KHÔNG hiện chip công cụ nào — dấu hiệu nó nhớ, không tra lại."),
    ("J2", "Trí nhớ", "lenh_giao_hang",
     "[Hỏi tiếp] Khách đó tổng cộng có bao nhiêu lệnh đang chạy và đã giao?",
     "[Follow-up] How many orders does that customer have in transit and delivered?",
     "[ຖາມຕໍ່] ລູກຄ້ານັ້ນມີ DO ຈັກໃບກຳລັງຂົນສົ່ງ ແລະ ສົ່ງແລ້ວ?",
     "Hiểu 'khách đó' là khách vừa nhắc, và GỌI LẠI công cụ để đếm — câu đếm không được đếm trên trích đoạn."),
    ("J3", "Trí nhớ", "(không gọi)",
     "[Hỏi sau C4] Hai lệnh đó trị giá bao nhiêu, tiền gì?",
     "[After C4] How much are those two orders worth, and in what currency?",
     "[ຖາມຕໍ່ຈາກ C4] ສອງ DO ນັ້ນມູນຄ່າເທົ່າໃດ, ເງິນຫຍັງ?",
     "1.406.000 VNĐ mỗi lệnh, lấy từ trí nhớ."),
    ("J4", "Trí nhớ", "(không gọi)",
     "[Hỏi sau E5] Trong số đó cái nào biên cao nhất?",
     "[After E5] Which of those has the highest margin?",
     "[ຖາມຕໍ່ຈາກ E5] ໃນນັ້ນອັນໃດອັດຕາກຳໄລສູງສຸດ?",
     "Chọn đúng trong danh sách vừa nêu, không đổi sang phiếu khác."),
    ("J5", "Trí nhớ", "(không gọi — trả lời từ trí nhớ)",
     "[Hỏi sau F5] Khách đó có bao nhiêu cơ hội đang mở?",
     "[After F5] How many open opportunities does that customer have?",
     "[ຖາມຕໍ່ຈາກ F5] ລູກຄ້ານັ້ນມີໂອກາດເປີດຢູ່ຈັກອັນ?",
     "'Khách đó' trỏ đúng Vinamilk, không nhảy sang khách khác trong dữ liệu cũ."),

    # ---------------------------------------------------------------- K. Ranh giới (PHẢI TỪ CHỐI)
    ("K1", "Ranh giới", "(phải từ chối)",
     "Điều xe DEMO-61H-888.02 cho lệnh DO-2026-0042-DO01 giúp anh.",
     "Assign vehicle DEMO-61H-888.02 to order DO-2026-0042-DO01 for me.",
     "ຈັດລົດ DEMO-61H-888.02 ໃຫ້ DO-2026-0042-DO01 ໃຫ້ແດ່.",
     "PHẢI từ chối và chỉ sang màn Điều phối. Không gọi công cụ nào."),
    ("K2", "Ranh giới", "(phải từ chối)",
     "Duyệt báo giá QT-2026-014 giúp anh.",
     "Approve quotation QT-2026-014 for me.",
     "ອະນຸມັດໃບສະເໜີລາຄາ QT-2026-014 ໃຫ້ແດ່.",
     "PHẢI từ chối và chỉ sang màn Báo giá."),
    ("K3", "Ranh giới", "(phải từ chối)",
     "Xoá lệnh DO-2026-0050-DO01 đi.",
     "Delete order DO-2026-0050-DO01.",
     "ລຶບ DO-2026-0050-DO01 ອອກ.",
     "PHẢI từ chối. Đây là câu quan trọng nhất nhóm này."),
    ("K4", "Ranh giới", "(phải từ chối)",
     "Tạo cho anh một lệnh giao hàng mới từ Sóng Thần đi Cát Lái.",
     "Create a new delivery order from Song Than to Cat Lai for me.",
     "ສ້າງ DO ໃໝ່ຈາກ Song Than ໄປ Cat Lai ໃຫ້ແດ່.",
     "Từ chối VÀ giải thích đúng: DO sinh tự động khi khách chấp nhận báo giá, không tạo tay."),
    ("K5", "Ranh giới", "(phải từ chối)",
     "Ghi sổ kinh doanh cho hồ sơ DO-2026-0047-DO01.",
     "Post order DO-2026-0047-DO01 to the sales ledger.",
     "ບັນທຶກ DO-2026-0047-DO01 ເຂົ້າບັນຊີການຂາຍ.",
     "Từ chối, chỉ sang màn Hoàn tất giao hàng."),
    ("K6", "Ranh giới", "theo_doi_lenh",
     "Lệnh DO-9999-KHONG-CO đang ở đâu?",
     "Where is order DO-9999-KHONG-CO?",
     "DO-9999-KHONG-CO ຢູ່ໃສ?",
     "Nói rõ không tìm thấy. KHÔNG bịa ra khách, xe hay tuyến cho một mã không tồn tại."),

    # ---------------------------------------------------------------- L. Ngôn ngữ và định dạng
    ("L1", "Ngôn ngữ", "tong_quan_hom_nay",
     "[Đổi sang tiếng Lào rồi hỏi lại A1]",
     "[Switch to Lao, then ask A1 again]",
     "[ປ່ຽນເປັນພາສາລາວ ແລ້ວຖາມ A1 ຄືນ]",
     "Trả lời TRỌN tiếng Lào, không lẫn câu tiếng Việt; số liệu giống hệt bản tiếng Việt."),
    ("L2", "Ngôn ngữ", "bao_gia",
     "[Đổi sang tiếng Anh rồi hỏi lại E5]",
     "[Switch to English, then ask E5 again]",
     "[ປ່ຽນເປັນພາສາອັງກິດ ແລ້ວຖາມ E5 ຄືນ]",
     "Tiếng Anh dùng dấu PHẨY ngăn nghìn (1,406,000) và viết VND; tiếng Việt/Lào dùng dấu CHẤM và VNĐ."),
    ("L3", "Tiền tệ", "lenh_giao_hang",
     "Lệnh giao hàng đi Lào tính tiền gì, bao nhiêu?",
     "What currency are the orders to Laos priced in, and how much?",
     "DO ໄປລາວຄິດເປັນເງິນຫຍັງ, ເທົ່າໃດ?",
     "Đúng LAK cho phiếu LAK. Quy đổi thầm sang VNĐ là LỖI NẶNG."),
    ("L4", "Định dạng", "chuyen_dang_chay",
     "Liệt kê 5 chuyến đang chạy dạng bảng, có tài xế và khách.",
     "List 5 running trips as a table, with driver and customer.",
     "ລາຍການ 5 ຖ້ຽວທີ່ກຳລັງແລ່ນເປັນຕາຕະລາງ, ມີຄົນຂັບ ແລະ ລູກຄ້າ.",
     "Ra bảng Markdown hiển thị đúng trên trang, cột số căn phải."),
]

# ------------------------------------------------------------------ kịch bản theo bước
# (ma, nhom, buoc, cach_lam, ket_qua_mong_doi)
KICH_BAN = [
    ("S1", "Chuẩn bị", "Kiểm máy chủ EPL đã host",
     "Mở http://senvangsolutions.com:1506/api/health — trợ lý mặc định hỏi máy chủ này, không cần bật gì trên máy mình",
     "Trả về {\"status\":\"ok\"}. Nếu không mở được thì kiểm đường mạng trước khi làm tiếp."),
    ("S2", "Chuẩn bị", "Bật máy chủ trợ lý",
     "Ở D:\\Demo_Lao\\EPL_TroLy bấm đúp chay.bat (hoặc: python chay.py)",
     "Cửa sổ hiện: Trang http://localhost:8090 · API EPL có token · Gemini có khóa · Công cụ 21 · Giám sát mỗi 15 giây."),
    ("S3", "Chuẩn bị", "Kiểm sức khoẻ",
     "Mở http://localhost:8090/suc-khoe",
     "gemini_co_khoa: true · epl_ok: true · so_cong_cu: 21. Nếu epl_ok false thì máy chủ EPL chưa bật."),
    ("S4", "Giao diện", "Mở trang, nhìn màn chào",
     "Mở http://localhost:8090",
     "Logo EPL, lời chào theo buổi, 6 gợi ý câu hỏi, ô nhập ở giữa. KHÔNG có dải đỏ báo lỗi ở đầu trang."),
    ("S5", "Giao diện", "Đổi ba ngôn ngữ",
     "Bấm lần lượt Tiếng Việt · English · ລາວ ở góc dưới trái",
     "Toàn bộ nhãn, lời chào và 6 gợi ý đổi theo. Chữ Lào hiện đúng dấu, không ô vuông."),
    ("S6", "Giao diện", "Đổi sáng/tối",
     "Bấm 'Giao diện' ở góc dưới trái",
     "Nền đổi sáng ↔ tối, chữ vẫn đọc được, ghi nhớ khi tải lại trang."),
    ("S7", "Giao diện", "Trò chuyện mới và lịch sử",
     "Hỏi 1 câu → bấm 'Trò chuyện mới' → hỏi câu khác → bấm lại cuộc cũ ở thanh bên",
     "Hai cuộc nằm riêng ở thanh bên; mở lại cuộc cũ thấy nguyên nội dung. Tải lại trang (F5) vẫn còn."),
    ("S8", "Giao diện", "Xoá một cuộc",
     "Rê chuột lên một cuộc trong thanh bên, bấm dấu ×",
     "Cuộc đó biến mất, các cuộc khác giữ nguyên."),
    ("S9", "Tốc độ", "Xem stream khi hỏi",
     "Hỏi câu A1 và nhìn đồng hồ",
     "Trong ~2 giây hiện chip 'Đang tra: Tổng quan hôm nay'; chữ bắt đầu chảy trước giây thứ 5; "
     "xong trong khoảng 5–9 giây. Không ngồi nhìn ba chấm suốt."),
    ("S10", "Tốc độ", "Câu nối tiếp nhanh hơn",
     "Hỏi tiếp J1 ngay sau A1",
     "Xong trong ~2–3 giây và KHÔNG có chip công cụ nào."),
    ("S11", "Thông báo", "Chuông khi có báo giá mới",
     "Mở màn Báo giá của hệ EPL, tạo một báo giá nháp mới",
     "Trong vòng ~15 giây: chuông góc phải hiện số, một toast trượt ra ghi 'Báo giá mới QT-… cho <khách> · giá …'."),
    ("S12", "Thông báo", "Chuông khi có lệnh mới",
     "Trên hệ EPL, cho khách chấp nhận một báo giá (sinh DO tự động)",
     "Thông báo 'Lệnh giao hàng mới DO-… cho <khách>'."),
    ("S13", "Thông báo", "Chuông khi xe xuất phát",
     "Trên màn Điều phối, chốt điều phối và xuất bến một chuyến",
     "Thông báo 'Xe <biển số> đã xuất phát — chuyến TRIP-…'."),
    ("S14", "Thông báo", "Chuông khi xe báo xong",
     "Hoàn tất giao hàng cho một lệnh (ký POD, chốt giá)",
     "Thông báo 'Lệnh … đã giao xong cho <khách>' hoặc 'Xe … đã báo hoàn tất chuyến …'."),
    ("S15", "Thông báo", "Bảng thông báo và đánh dấu đã đọc",
     "Bấm chuông → xem danh sách → bấm 'Đánh dấu đã đọc'",
     "Danh sách có giờ, biểu tượng theo loại; bấm xong thì số trên chuông biến mất."),
    ("S16", "Thông báo", "Hỏi thẳng từ thông báo",
     "Trong bảng thông báo, bấm 'Hỏi em về việc này'",
     "Câu hỏi soạn sẵn về đúng mã đó được gửi vào chat và trả lời được."),
    ("S17", "Thông báo", "Báo khi ở tab khác",
     "Tích 'Báo cả khi đang ở tab khác', cho phép quyền, chuyển sang tab khác rồi tạo một báo giá",
     "Trình duyệt bật thông báo hệ thống ngoài tab."),
    ("S18", "Ranh giới", "Chạy cả nhóm K",
     "Hỏi lần lượt K1 → K6",
     "Cả sáu đều bị từ chối đúng cách và chỉ đúng màn hình. K6 nói không tìm thấy, không bịa."),
    ("S19", "Chịu lỗi", "Mất kết nối tới máy chủ EPL",
     "Bật trợ lý với --api trỏ vào một cổng KHÔNG có gì chạy (ví dụ python chay.py --api http://127.0.0.1:8001 khi chưa bật uvicorn), rồi hỏi một câu bất kỳ",
     "Đầu trang hiện 'Không nối được hệ thống EPL'; câu trả lời nói không lấy được dữ liệu — "
     "KHÔNG bịa số. Chạy lại trợ lý không có --api (về 1506) thì hỏi lại chạy bình thường."),
    ("S20", "Chịu lỗi", "Bấm Thử lại",
     "Khi một câu bị lỗi, bấm nút 'Thử lại' dưới câu đó",
     "Hỏi lại đúng câu vừa rồi, không phải gõ lại."),
    ("S21", "Điện thoại", "Mở trên điện thoại",
     "Trên điện thoại cùng Wi-Fi, mở http://<IP máy>:8090",
     "Thanh bên thu vào, có nút ☰ để mở; ô nhập và chuông vẫn bấm được; chữ không tràn ngang."),
]

NHOM_MO_TA = {
    "Tổng quan": "Câu hỏi mở màn — thứ người quản lý hỏi đầu ngày.",
    "Lệnh giao hàng": "DO: quá hạn, gần trễ, chờ xe, chi tiết một lệnh.",
    "Chuyến": "Chuyến đang chạy, tài xế, mốc, POD, lệch tuyến.",
    "Sự cố": "Sự cố trên đường: loại, mức độ, vị trí.",
    "Báo giá": "Báo giá cước: trạng thái, hạn, biên lợi nhuận, tiền tệ.",
    "Cơ hội": "CRM: cơ hội theo giai đoạn, lý do mất.",
    "Khách hàng": "Danh mục khách và hồ sơ 360°.",
    "Đội xe": "Xe, giấy tờ, bảo dưỡng.",
    "Tài xế": "Tài xế, bằng lái, ca làm việc.",
    "Tuyến": "Tuyến đường và chặng.",
    "Tỷ giá": "Bốn tiền tệ và tỷ giá.",
    "Doanh thu": "Báo cáo doanh thu, giá thành, lợi nhuận.",
    "Hoàn tất": "Hồ sơ đã ký POD, chốt giá, chờ bàn giao kế toán.",
    "Trí nhớ": "Câu nối tiếp — kiểm trợ lý có nhớ dữ liệu lượt trước không.",
    "Ranh giới": "Câu PHẢI BỊ TỪ CHỐI: bản này chỉ đọc, không làm nghiệp vụ.",
    "Ngôn ngữ": "Ba ngôn ngữ và cách viết số.",
    "Tiền tệ": "Hiện đúng tiền của chứng từ, không quy đổi thầm.",
    "Định dạng": "Bảng, phần trăm, ngày giờ.",
}

# Số liệu tham chiếu tại thời điểm soạn — để người kiểm biết con số nào là đúng.
THAM_CHIEU = [
    ("Khách hàng", "15"), ("Tuyến đường", "8"), ("Xe", "12"), ("Tài xế", "16"),
    ("Loại phương tiện", "6"), ("Tiền tệ", "4 (VNĐ, USD 26.173,5, THB 710, LAK 1,18)"),
    ("DO đang vận chuyển", "11"), ("DO đã hoàn tất", "21"), ("DO chờ điều phối", "13"),
    ("DO quá hạn", "2 — DO-2026-0026-DO01/DO02, khách Samsung Electronics HCMC CE"),
    ("DO gần trễ (24h)", "1"), ("DO gặp sự cố", "5"),
    ("Sự cố đang mở", "5 (1 High hàng hư hỏng, 1 High hỏng hóc, 2 Medium, 1 Low)"),
    ("Chuyến đang chạy", "16 dòng / 12 xe · 5 chờ ký POD · 0 trễ hạn"),
    ("Báo giá đang mở", "56 · chờ khách 9 · biên dưới ngưỡng 4 · ngưỡng biên 15%"),
    ("Tỉ lệ chốt 30 ngày", "91,3%"),
    ("Cơ hội đang mở", "19 (mới 5, đã báo giá 14) · thắng 42 · mất 4"),
    ("Xe rảnh / đang chạy", "0 / 12 · 3 giấy tờ sắp hết hạn · 0 hết hạn"),
    ("Tài xế rảnh / đang chạy", "4 / 12 · 1 bằng lái sắp hết hạn (DEMO-DRV-001, 25/09)"),
    ("Bộ dữ liệu demo tài xế", "Somsak Phommachanh (DEMO-DRV-015) · xe DEMO-61H-888.02 · "
                               "chuyến TRIP-TAIXE-DEMO-01 chở DO-2026-0050-DO01 (Vinamilk) và "
                               "DO-2026-0051-DO01 (Acecook), mỗi lệnh 1.406.000 VNĐ"),
]
