VERSION = "005_tms_dispatch_eligibility"


def statements(_dialect, direction="upgrade"):
    if direction == "rollback":
        return [
            "DROP TABLE IF EXISTS resource_assignments",
            "DROP TABLE IF EXISTS warehouse_appointments",
            "DROP TABLE IF EXISTS driver_qualifications",
            "ALTER TABLE vehicles DROP COLUMN IF EXISTS pallet_capacity",
        ]
    return [
        "ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS pallet_capacity INTEGER NOT NULL DEFAULT 0",
        """CREATE TABLE IF NOT EXISTS driver_qualifications (
            driver_id TEXT PRIMARY KEY REFERENCES drivers(id), license_type TEXT NOT NULL,
            valid_from TIMESTAMP NOT NULL, valid_to TIMESTAMP NOT NULL,
            status TEXT NOT NULL DEFAULT 'active', verified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            verified_by TEXT NOT NULL DEFAULT 'system', CHECK (valid_to >= valid_from)
        )""",
        """CREATE TABLE IF NOT EXISTS warehouse_appointments (
            id TEXT PRIMARY KEY, freight_order_id TEXT NOT NULL REFERENCES freight_orders(id),
            appointment_type TEXT NOT NULL, location_id TEXT NOT NULL REFERENCES locations(id),
            scheduled_start TIMESTAMP NOT NULL, scheduled_end TIMESTAMP NOT NULL,
            status TEXT NOT NULL DEFAULT 'booked', version INTEGER NOT NULL DEFAULT 1,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by TEXT NOT NULL DEFAULT 'system',
            CONSTRAINT uq_fo_appointment_type UNIQUE (freight_order_id, appointment_type),
            CHECK (appointment_type IN ('pickup', 'delivery')), CHECK (scheduled_end > scheduled_start)
        )""",
        """CREATE TABLE IF NOT EXISTS resource_assignments (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            freight_order_id TEXT NOT NULL UNIQUE REFERENCES freight_orders(id),
            vehicle_id TEXT NOT NULL REFERENCES vehicles(id), driver_id TEXT NOT NULL REFERENCES drivers(id),
            assignment_start TIMESTAMP NOT NULL, assignment_end TIMESTAMP NOT NULL,
            status TEXT NOT NULL DEFAULT 'active', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by TEXT NOT NULL DEFAULT 'system', CHECK (assignment_end > assignment_start)
        )""",
        "CREATE INDEX IF NOT EXISTS ix_warehouse_appointments_order ON warehouse_appointments(freight_order_id)",
        "CREATE INDEX IF NOT EXISTS ix_resource_assignments_vehicle_time ON resource_assignments(vehicle_id, assignment_start, assignment_end)",
        "CREATE INDEX IF NOT EXISTS ix_resource_assignments_driver_time ON resource_assignments(driver_id, assignment_start, assignment_end)",
    ]


def upgrade_sqlite(connection):
    vehicle_exists = connection.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name='vehicles'"
    ).fetchone()
    columns = {row[1] for row in connection.execute('PRAGMA table_info("vehicles")')} if vehicle_exists else set()
    if vehicle_exists and "pallet_capacity" not in columns:
        connection.execute("ALTER TABLE vehicles ADD COLUMN pallet_capacity INTEGER NOT NULL DEFAULT 0")
    sqlite_sql = statements("sqlite", "upgrade")[1:]
    for sql in sqlite_sql:
        connection.execute(sql.replace("INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY", "INTEGER PRIMARY KEY AUTOINCREMENT"))


def rollback_sqlite(connection):
    for sql in statements("sqlite", "rollback")[:3]:
        connection.execute(sql)
    vehicle_exists = connection.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name='vehicles'"
    ).fetchone()
    columns = {row[1] for row in connection.execute('PRAGMA table_info("vehicles")')} if vehicle_exists else set()
    if vehicle_exists and "pallet_capacity" in columns:
        connection.execute("ALTER TABLE vehicles DROP COLUMN pallet_capacity")
