VERSION = "006_tms_execution_events"
EVENT_TYPES = {"check_in", "pickup", "departure", "arrival", "unloading", "delivered",
               "incident", "delay", "route_deviation"}
SOURCES = {"device", "manual"}

EXPECTED_COLUMNS = {
    "transport_events": {"id", "freight_order_id", "event_type", "event_time", "lat", "lng",
                         "speed_kmh", "distance_km", "eta", "location_text", "source", "device_id",
                         "reason", "note", "idempotency_key", "payload_hash", "recorded_at", "recorded_by"},
    "transport_event_documents": {"id", "event_id", "document_type", "storage_url", "file_name",
                                  "mime_type", "checksum", "uploaded_at", "uploaded_by"},
    "freight_order_legacy_links": {"freight_order_id", "delivery_order_id"},
}
EXPECTED_INDEXES = {"ix_transport_events_order_time", "ix_transport_event_documents_event"}
_SQLITE_META = {
    "transport_events": {
        "id": ("TEXT", 0, None, 1), "freight_order_id": ("TEXT", 1, None, 0),
        "event_type": ("TEXT", 1, None, 0), "event_time": ("TIMESTAMP", 1, None, 0),
        "lat": ("DOUBLE PRECISION", 0, None, 0), "lng": ("DOUBLE PRECISION", 0, None, 0),
        "speed_kmh": ("DOUBLE PRECISION", 0, None, 0), "distance_km": ("DOUBLE PRECISION", 0, None, 0),
        "eta": ("TEXT", 0, None, 0), "location_text": ("TEXT", 0, None, 0),
        "source": ("TEXT", 1, None, 0), "device_id": ("TEXT", 0, None, 0),
        "reason": ("TEXT", 0, None, 0), "note": ("TEXT", 0, None, 0),
        "idempotency_key": ("TEXT", 1, None, 0), "payload_hash": ("TEXT", 1, None, 0),
        "recorded_at": ("TIMESTAMP", 1, "CURRENT_TIMESTAMP", 0), "recorded_by": ("TEXT", 1, None, 0),
    },
    "transport_event_documents": {
        "id": ("INTEGER", 0, None, 1), "event_id": ("TEXT", 1, None, 0),
        "document_type": ("TEXT", 1, None, 0), "storage_url": ("TEXT", 1, None, 0),
        "file_name": ("TEXT", 0, None, 0), "mime_type": ("TEXT", 0, None, 0),
        "checksum": ("TEXT", 1, None, 0), "uploaded_at": ("TIMESTAMP", 1, "CURRENT_TIMESTAMP", 0),
        "uploaded_by": ("TEXT", 1, None, 0),
    },
    "freight_order_legacy_links": {
        "freight_order_id": ("TEXT", 0, None, 1), "delivery_order_id": ("TEXT", 1, None, 0),
    },
}


def statements(_dialect, direction="upgrade"):
    if direction == "rollback":
        return [
            "DROP TABLE IF EXISTS transport_event_documents",
            "DROP TABLE IF EXISTS transport_events",
            "DROP TABLE IF EXISTS freight_order_legacy_links",
        ]
    return [
        """CREATE TABLE IF NOT EXISTS freight_order_legacy_links (
            freight_order_id TEXT PRIMARY KEY REFERENCES freight_orders(id),
            delivery_order_id TEXT NOT NULL UNIQUE REFERENCES delivery_orders(id)
        )""",
        """CREATE TABLE IF NOT EXISTS transport_events (
            id TEXT PRIMARY KEY,
            freight_order_id TEXT NOT NULL REFERENCES freight_orders(id),
            event_type TEXT NOT NULL,
            event_time TIMESTAMP NOT NULL,
            lat DOUBLE PRECISION,
            lng DOUBLE PRECISION,
            speed_kmh DOUBLE PRECISION,
            distance_km DOUBLE PRECISION,
            eta TEXT,
            location_text TEXT,
            source TEXT NOT NULL,
            device_id TEXT,
            reason TEXT,
            note TEXT,
            idempotency_key TEXT NOT NULL,
            payload_hash TEXT NOT NULL,
            recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            recorded_by TEXT NOT NULL,
            CONSTRAINT uq_transport_event_idempotency UNIQUE (freight_order_id, idempotency_key),
            CHECK (event_type IN ('check_in', 'pickup', 'departure', 'arrival', 'unloading', 'delivered', 'incident', 'delay', 'route_deviation')),
            CHECK (source IN ('device', 'manual')),
            CHECK (lat IS NULL OR (lat >= -90 AND lat <= 90)),
            CHECK (lng IS NULL OR (lng >= -180 AND lng <= 180)),
            CHECK (speed_kmh IS NULL OR speed_kmh >= 0),
            CHECK (distance_km IS NULL OR distance_km >= 0)
        )""",
        """CREATE TABLE IF NOT EXISTS transport_event_documents (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            event_id TEXT NOT NULL REFERENCES transport_events(id),
            document_type TEXT NOT NULL,
            storage_url TEXT NOT NULL,
            file_name TEXT,
            mime_type TEXT,
            checksum TEXT NOT NULL,
            uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            uploaded_by TEXT NOT NULL
        )""",
        "CREATE INDEX IF NOT EXISTS ix_transport_events_order_time ON transport_events(freight_order_id, event_time, recorded_at)",
        "CREATE INDEX IF NOT EXISTS ix_transport_event_documents_event ON transport_event_documents(event_id)",
    ]


def upgrade_sqlite(connection):
    for table in EXPECTED_COLUMNS:
        if connection.execute(
            "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (table,)
        ).fetchone():
            _validate_sqlite_table(connection, table)
    for sql in statements("sqlite", "upgrade"):
        connection.execute(sql.replace(
            "INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY",
            "INTEGER PRIMARY KEY AUTOINCREMENT",
        ))
    validate_sqlite(connection)


def rollback_sqlite(connection):
    for sql in statements("sqlite", "rollback"):
        connection.execute(sql)


def _validate_sqlite_table(connection, table):
    columns = {row[1]: (row[2].upper(), row[3], row[4], row[5])
               for row in connection.execute(f'PRAGMA table_info("{table}")')}
    if columns != _SQLITE_META[table]:
        raise RuntimeError(f"{table} schema mismatch")
    create_sql = connection.execute(
        "SELECT sql FROM sqlite_master WHERE type='table' AND name=?", (table,)
    ).fetchone()[0].lower().replace('"', "")
    compact_sql = " ".join(create_sql.split())
    required_fragments = {
        "transport_events": ("unique (freight_order_id, idempotency_key)", "check (event_type in",
                             "check (source in", "check (lat is null or (lat >= -90 and lat <= 90))",
                             "check (lng is null or (lng >= -180 and lng <= 180))",
                             "check (speed_kmh is null or speed_kmh >= 0)",
                             "check (distance_km is null or distance_km >= 0)"),
        "transport_event_documents": ("references transport_events(id)",),
        "freight_order_legacy_links": ("delivery_order_id text not null unique references delivery_orders(id)",
                                       "references freight_orders(id)"),
    }[table]
    if any(fragment not in create_sql for fragment in required_fragments):
        raise RuntimeError(f"{table} schema mismatch")
    if table == "transport_events":
        event_enum = "check (event_type in (" + ", ".join(f"'{value}'" for value in (
            "check_in", "pickup", "departure", "arrival", "unloading", "delivered",
            "incident", "delay", "route_deviation")) + "))"
        source_enum = "check (source in ('device', 'manual'))"
        if event_enum not in compact_sql or source_enum not in compact_sql:
            raise RuntimeError(f"{table} schema mismatch")
    expected_fks = {
        "transport_events": {("freight_order_id", "freight_orders", "id")},
        "transport_event_documents": {("event_id", "transport_events", "id")},
        "freight_order_legacy_links": {("freight_order_id", "freight_orders", "id"),
                                       ("delivery_order_id", "delivery_orders", "id")},
    }[table]
    actual_fks = {(row[3], row[2], row[4]) for row in connection.execute(f'PRAGMA foreign_key_list("{table}")')}
    if actual_fks != expected_fks:
        raise RuntimeError(f"{table} schema mismatch")
    unique_columns = {
        tuple(item[2] for item in connection.execute(f'PRAGMA index_info("{row[1]}")'))
        for row in connection.execute(f'PRAGMA index_list("{table}")') if row[2]
    }
    expected_unique = {
        "transport_events": {("id",), ("freight_order_id", "idempotency_key")},
        "transport_event_documents": set(),
        "freight_order_legacy_links": {("freight_order_id",), ("delivery_order_id",)},
    }[table]
    # INTEGER PRIMARY KEY is represented by the rowid rather than a unique index.
    if table == "transport_event_documents":
        unique_columns.discard(("id",))
    if unique_columns != expected_unique:
        raise RuntimeError(f"{table} schema mismatch")


def validate_sqlite(connection):
    for table in EXPECTED_COLUMNS:
        _validate_sqlite_table(connection, table)
    indexes = {row[0] for row in connection.execute(
        "SELECT name FROM sqlite_master WHERE type='index'"
    )}
    if not EXPECTED_INDEXES <= indexes:
        raise RuntimeError("transport_events schema mismatch")
    ordered = [row[2] for row in connection.execute('PRAGMA index_info("ix_transport_events_order_time")')]
    if ordered != ["freight_order_id", "event_time", "recorded_at"]:
        raise RuntimeError("transport_events schema mismatch")
    document_order = [row[2] for row in connection.execute('PRAGMA index_info("ix_transport_event_documents_event")')]
    if document_order != ["event_id"]:
        raise RuntimeError("transport_event_documents schema mismatch")


def validate_postgresql(connection):
    rows = list(connection.execute(
        __import__("sqlalchemy").text(
            "SELECT table_name, column_name, data_type, is_nullable, column_default, is_identity FROM information_schema.columns "
            "WHERE table_schema='public' AND table_name IN "
            "('transport_events','transport_event_documents','freight_order_legacy_links')"
        )
    ))
    sqlite_to_pg = {"TEXT": "text", "TIMESTAMP": "timestamp without time zone",
                    "DOUBLE PRECISION": "double precision", "INTEGER": "integer"}
    actual = {(row[0], row[1]): (row[2].lower(), row[3], row[4], row[5]) for row in rows}
    expected = {}
    for table, columns in _SQLITE_META.items():
        for column, (declared_type, not_null, default, pk) in columns.items():
            nullable = "NO" if not_null or pk else "YES"
            identity = "YES" if table == "transport_event_documents" and column == "id" else "NO"
            expected[(table, column)] = (sqlite_to_pg[declared_type], nullable, default, identity)
    if not set(expected) <= set(actual):
        raise RuntimeError("transport_events schema mismatch")
    for key, (data_type, nullable, default, identity) in expected.items():
        got_type, got_nullable, got_default, got_identity = actual[key]
        default_matches = (default is None and got_default is None) or (
            default == "CURRENT_TIMESTAMP" and got_default is not None and "current_timestamp" in got_default.lower()
        )
        if (got_type, got_nullable, got_identity) != (data_type, nullable, identity) or not default_matches:
            raise RuntimeError(f"{key[0]} schema mismatch")
    constraint_rows = list(connection.execute(
        __import__("sqlalchemy").text(
            "SELECT tc.table_name, tc.constraint_name, tc.constraint_type, "
            "(SELECT string_agg(k.column_name, ',' ORDER BY k.ordinal_position) FROM information_schema.key_column_usage k "
            " WHERE k.constraint_schema=tc.constraint_schema AND k.constraint_name=tc.constraint_name) AS source_columns, "
            "(SELECT min(c.table_name) FROM information_schema.constraint_column_usage c "
            " WHERE c.constraint_schema=tc.constraint_schema AND c.constraint_name=tc.constraint_name) AS target_table, "
            "(SELECT string_agg(c.column_name, ',' ORDER BY c.column_name) FROM information_schema.constraint_column_usage c "
            " WHERE c.constraint_schema=tc.constraint_schema AND c.constraint_name=tc.constraint_name) AS target_columns, "
            "cc.check_clause FROM information_schema.table_constraints tc "
            "LEFT JOIN information_schema.check_constraints cc ON cc.constraint_schema=tc.constraint_schema AND cc.constraint_name=tc.constraint_name "
            "WHERE tc.table_schema='public' AND tc.table_name IN ('transport_events','transport_event_documents','freight_order_legacy_links') "
        )
    ))
    keys = {(row[0], row[2], row[3], row[4], row[5]) for row in constraint_rows if row[2] != "CHECK"}
    expected_keys = {
        ("transport_events", "PRIMARY KEY", "id", "transport_events", "id"),
        ("transport_events", "UNIQUE", "freight_order_id,idempotency_key", "transport_events", "freight_order_id,idempotency_key"),
        ("transport_events", "FOREIGN KEY", "freight_order_id", "freight_orders", "id"),
        ("transport_event_documents", "PRIMARY KEY", "id", "transport_event_documents", "id"),
        ("transport_event_documents", "FOREIGN KEY", "event_id", "transport_events", "id"),
        ("freight_order_legacy_links", "PRIMARY KEY", "freight_order_id", "freight_order_legacy_links", "freight_order_id"),
        ("freight_order_legacy_links", "UNIQUE", "delivery_order_id", "freight_order_legacy_links", "delivery_order_id"),
        ("freight_order_legacy_links", "FOREIGN KEY", "freight_order_id", "freight_orders", "id"),
        ("freight_order_legacy_links", "FOREIGN KEY", "delivery_order_id", "delivery_orders", "id"),
    }
    if not expected_keys <= keys:
        raise RuntimeError("transport_events schema mismatch")
    _validate_postgresql_checks(constraint_rows)
    indexes = {row[0]: row[1].lower() for row in connection.execute(
        __import__("sqlalchemy").text(
            "SELECT indexname, indexdef FROM pg_indexes WHERE schemaname='public' AND tablename IN "
            "('transport_events','transport_event_documents')"
        )
    )}
    if (not EXPECTED_INDEXES <= indexes.keys()
            or "(freight_order_id, event_time, recorded_at)" not in indexes["ix_transport_events_order_time"]
            or "(event_id)" not in indexes["ix_transport_event_documents_event"]):
        raise RuntimeError("transport_events schema mismatch")


def _validate_postgresql_checks(constraint_rows):
    import re
    checks = [
        (row[0], (row[6] or "").lower())
        for row in constraint_rows
        if row[2] == "CHECK"
        and row[0] == "transport_events"
        and " is not null" not in (row[6] or "").lower()
    ]
    def clause_for(column):
        matches = [clause for _, clause in checks if re.search(rf"\b{column}\b", clause)]
        if len(matches) != 1:
            raise RuntimeError("transport_events schema mismatch")
        return matches[0]
    if set(re.findall(r"'([^']+)'", clause_for("event_type"))) != EVENT_TYPES:
        raise RuntimeError("transport_events schema mismatch")
    if set(re.findall(r"'([^']+)'", clause_for("source"))) != SOURCES:
        raise RuntimeError("transport_events schema mismatch")
    predicates = {
        "lat": ("is null", ">= -90", "<= 90"),
        "lng": ("is null", ">= -180", "<= 180"),
        "speed_kmh": ("is null", ">= 0"),
        "distance_km": ("is null", ">= 0"),
    }
    for column, required in predicates.items():
        normalized = re.sub(r"::[a-z ]+", " ", clause_for(column))
        normalized = re.sub(r"[()\"']", " ", normalized)
        normalized = " ".join(normalized.split())
        if any(fragment not in normalized for fragment in required):
            raise RuntimeError("transport_events schema mismatch")
