VERSION = "021_vehicle_maintenance"

from sqlalchemy import text


REQUEST_TABLE = "vehicle_maintenance_requests"
COST_TABLE = "vehicle_maintenance_cost_lines"


def _request_sql():
    return f"""
        CREATE TABLE IF NOT EXISTS {REQUEST_TABLE} (
            id VARCHAR(128) PRIMARY KEY,
            request_no VARCHAR(128) NOT NULL UNIQUE,
            vehicle_id VARCHAR NOT NULL REFERENCES vehicles(id),
            category VARCHAR(32) NOT NULL DEFAULT 'corrective',
            priority VARCHAR(20) NOT NULL DEFAULT 'normal',
            planned_start TIMESTAMP NOT NULL,
            planned_end TIMESTAMP NOT NULL,
            actual_start TIMESTAMP,
            actual_end TIMESTAMP,
            description TEXT NOT NULL,
            cause TEXT,
            odometer_km FLOAT,
            workshop VARCHAR(255),
            currency_code VARCHAR(3) NOT NULL DEFAULT 'VND',
            estimated_total NUMERIC(24,6) NOT NULL DEFAULT 0,
            actual_total NUMERIC(24,6) NOT NULL DEFAULT 0,
            next_maintenance_date VARCHAR(10),
            status VARCHAR(20) NOT NULL DEFAULT 'requested',
            cancellation_reason TEXT,
            version INTEGER NOT NULL DEFAULT 1,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by VARCHAR(128) NOT NULL DEFAULT 'system',
            updated_by VARCHAR(128) NOT NULL DEFAULT 'system',
            approved_at TIMESTAMP,
            approved_by VARCHAR(128),
            completed_at TIMESTAMP,
            completed_by VARCHAR(128),
            CONSTRAINT ck_vehicle_maintenance_period CHECK (planned_end > planned_start),
            CONSTRAINT ck_vehicle_maintenance_status CHECK (
                status IN ('requested','approved','in_progress','completed','cancelled')
            ),
            CONSTRAINT ck_vehicle_maintenance_version CHECK (version > 0)
        )
    """


def _cost_sql(dialect):
    identity = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if dialect == "postgresql" else "INTEGER PRIMARY KEY AUTOINCREMENT"
    return f"""
        CREATE TABLE IF NOT EXISTS {COST_TABLE} (
            id {identity},
            request_id VARCHAR(128) NOT NULL REFERENCES {REQUEST_TABLE}(id) ON DELETE CASCADE,
            category VARCHAR(32) NOT NULL DEFAULT 'other',
            description VARCHAR(500) NOT NULL,
            quantity NUMERIC(18,4) NOT NULL DEFAULT 1,
            unit VARCHAR(32) NOT NULL DEFAULT 'item',
            estimated_unit_cost NUMERIC(24,6) NOT NULL DEFAULT 0,
            estimated_total NUMERIC(24,6) NOT NULL DEFAULT 0,
            actual_unit_cost NUMERIC(24,6) NOT NULL DEFAULT 0,
            actual_total NUMERIC(24,6) NOT NULL DEFAULT 0,
            CONSTRAINT ck_vehicle_maintenance_cost_quantity CHECK (quantity > 0),
            CONSTRAINT ck_vehicle_maintenance_estimated_cost CHECK (estimated_unit_cost >= 0),
            CONSTRAINT ck_vehicle_maintenance_actual_cost CHECK (actual_unit_cost >= 0)
        )
    """


def statements(dialect, direction="upgrade"):
    if direction == "rollback":
        return [f"DROP TABLE IF EXISTS {COST_TABLE}", f"DROP TABLE IF EXISTS {REQUEST_TABLE}"]
    return [
        _request_sql(),
        _cost_sql(dialect),
        f"CREATE INDEX IF NOT EXISTS ix_vehicle_maintenance_vehicle_period ON {REQUEST_TABLE}(vehicle_id, planned_start, planned_end)",
    ]


def upgrade_sqlite(connection):
    for sql in statements("sqlite"):
        connection.execute(sql)
    validate_sqlite(connection)


def rollback_sqlite(connection):
    for sql in statements("sqlite", "rollback"):
        connection.execute(sql)


def validate_sqlite(connection):
    for table in (REQUEST_TABLE, COST_TABLE):
        if not connection.execute(
            "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (table,)
        ).fetchone():
            raise RuntimeError(f"{table} missing")


def validate_postgresql(connection):
    rows = connection.execute(text("""
        SELECT table_name FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name IN ('vehicle_maintenance_requests','vehicle_maintenance_cost_lines')
    """))
    if len(list(rows)) != 2:
        raise RuntimeError("vehicle maintenance tables missing")
